### ISSUE TITLE
[window_tab] 建议,是否可以记录上次打开的标签(支持多标签)

### ISSUE THREAD

**Issue by pro911** [obgnail/typora_plugin#180]
feat:
 能否实现,上次打开的目录及文件(多个文件),在原生设置里面是有,但没考虑打开多个文件, 插件支持标签后,建议是否可以恢复关闭时的打开多标签状态.目前默认是只保留了最后一个标签.
> 这可能对原生有一定的侵入.只是建议.

**Comment by obgnail** [comment]
@pro911 

你好，您的需求已经实现。

添加了 reopenClosedFiles 插件，其配置在 custom_plugin.toml 中：

```toml
############### reopenClosedFiles ###############
[reopenClosedFiles]
# 右键菜单中展示的名称
name = "打开上次退出时尚未关闭的标签页"
# 是否启用此自定义插件（此插件仅在window_tab启用时生效）
enable = true
# 插件配置
[reopenClosedFiles.config]
# 打开Typora自动打开
# 注意：只当双击typora.exe打开Typora时生效（打开特定文件时，自动打开上次退出时尚未关闭的标签页，明显不符合用户预期）
auto_reopen_when_init = true
# 快捷键
hotkey = ""
```

麻烦测试一下。有问题请在下面留言。
