### ISSUE TITLE
[feature] 换行时, 自动/一键在行末尾(换行符前)添加 两个空格

### ISSUE THREAD

**Issue by yiyungent** [obgnail/typora_plugin#202]
在 `Typora` 中，换行，会渲染为下一行，
而在标准 `Markdown` 规范中，还需要在 **换行符前** 跟至少两个空格，才能起到换行效果，
这点可以在 `vscode` 中看到效果，当然在 `GitHub` 中看不出来，
我现在在 `Typora` 中都是手动加上两个空格来起到换行效果的，希望能增加个自动加换行的功能，
为什么尽量兼容标准 `Markdown`, 我用的静态生成器 `Hexo` ，其中用的 `pandoc` 默认对于这种没有两个空格的情况就会不换行，而是在一行

![image](https://github.com/obgnail/typora_plugin/assets/16939388/579a4b97-fb2f-4da5-8c4f-4f6092acdc0c)

**Comment by obgnail** [comment]
这个需求听起来更像是要整一个 markdown lint 插件，一键修复 lint warn/error

**Comment by yiyungent** [comment]
> @yiyungent
> 
> 国庆有空，添加了 autoTrailingWhiteSpace 插件。麻烦试用一下。
> 
> 不过由于这个插件比较个性化，我设置为默认关闭了。需要您这边手动将 enable 置为 true。
> 
> 有问题可以在下面留言。
> 
> ```toml
> ############### autoTrailingWhiteSpace ###############
> # 此插件是为了满足Markdown换行语法，除非有特殊需求，否则不建议开启此插件
> # 参考：https://markdown.com.cn/basic-syntax/line-breaks.html
> [autoTrailingWhiteSpace]
> # 右键菜单中展示的名称
> name = "自动添加结尾空格"
> # 是否启用此自定义插件
> enable = false
> # 插件配置
> [autoTrailingWhiteSpace.config]
> # 快捷键
> hotkey = "ctrl+shift+j"
> ```

> 今天更新插件才发现还真有问题， 最后手动替换才更新好了

![image](https://github.com/obgnail/typora_plugin/assets/16939388/278e2d29-40ff-4c91-9be1-9cf420e62900)
![image](https://github.com/obgnail/typora_plugin/assets/16939388/3e0359cd-91af-4576-9b57-a6ec36126f14)

>  设置里启用了，发现按快捷键没反应啊， `git status` 也没 change, dalao  自测了吗，可行吗 ? 

![image](https://github.com/obgnail/typora_plugin/assets/16939388/8372a8d1-9945-40b8-a23e-1935ef106cff)



> PS: 其实 Typora 不只是这里做了变更，还有其它地方，可惜我忘了

**Comment by obgnail** [comment]
@yiyungent 

1. 【更新插件】之前确实写的有问题。一两个星期前修改了，后续应该不会出现此问题了。
2. 我这边测试是通过的。有可能是快捷键被占用了，你先试试右键菜单调用：右键菜单 -> 常用插件 -> 自定义插件 -> 自动添加结尾空格。
![Snipaste_2023-10-06_00-54-38](https://github.com/obgnail/typora_plugin/assets/48992887/4358081d-00dc-4690-9386-83059d154bfd)


如果还是不行，麻烦打开一下控制台看看有什么报错。

**Comment by obgnail** [comment]
@yiyungent 

我刚刚仔细看了一下，你把配置放错位置了

不是放到 settings.user.toml，而是 custom.user.toml

**Comment by obgnail** [comment]
![Snipaste_2023-10-06_01-01-22](https://github.com/obgnail/typora_plugin/assets/48992887/6077cc67-9374-4c16-9b91-0dc4585921ba)

**Comment by obgnail** [comment]
刚刚查了一下，更新插件的问题，和 https://github.com/obgnail/typora_plugin/issues/194 是一样的，两周前修复了。

而且现在开启了自动更新，默认会在你启动 Typora 5 分钟后检测更新。

当然，如果你不喜欢的话，可以关闭掉
```toml
############### pluginUpdater ###############
[pluginUpdater]
# 右键菜单中展示的名称
name = "升级插件"
# 是否启用此自定义插件
enable = true
[pluginUpdater.config]
# 升级时是否弹窗
#   1.always: 总是弹出
#   2.error: 只在异常时弹出
#   3.silent: 总是静默
#   4.echo: 立即回显
exec_show = "echo"
# 打开Typora时自动静默升级（若为false，则start_update_interval、auto_exec_show配置失效）
auto_update = true
# 打开Typora多长时间后，开始执行升级流程（单位：ms）
start_update_interval = 300000 # (1000 * 60 * 5)
# 自动升级时使用的回显方式
auto_exec_show = "silent"
```

**Comment by obgnail** [comment]
![Snipaste_2023-10-06_17-22-48](https://github.com/obgnail/typora_plugin/assets/48992887/4211abb8-efff-42b1-a5c4-938d56f4bd24)

**Comment by yiyungent** [comment]
谢谢dalao，我回去试试

**Comment by yiyungent** [comment]
很好，可以，成功了，也成功让我图片不显示了

![image](https://github.com/obgnail/typora_plugin/assets/16939388/d4f6353b-2e61-4fa2-bb2a-380e3960d392)

> 在 `Typora` 中，图片标识后不能加两个空格的，不然会渲染不出来，亲测

![image](https://github.com/obgnail/typora_plugin/assets/16939388/15cfaf27-858c-486c-b71d-c3f4890f8da6)
![image](https://github.com/obgnail/typora_plugin/assets/16939388/acac4f81-53f2-473d-855f-1ccb1170da17)

我的版本

![image](https://github.com/obgnail/typora_plugin/assets/16939388/16451d6b-1b1d-480b-985b-5655406d85c8)

**Comment by obgnail** [comment]
@yiyungent 

看起来是版本问题，我在 1.6.2 版本没有此问题。

有个问题：在 markdown 标准中，图片后面需不需要加两个空格？

**Comment by obgnail** [comment]
@yiyungent 

目前我还是给图片加了 tailing space，不过我兼容了旧版本的 Typora，使其添加了空格也不会显示失效。

麻烦先试用看看，如果有问题，请在下面反馈。

**Comment by obgnail** [comment]
顺便试试一键升级还有没有问题 :)

**Comment by yiyungent** [comment]
> 顺便试试一键升级还有没有问题 :)


![image](https://github.com/obgnail/typora_plugin/assets/16939388/096ba388-f846-46fd-b362-133217f2fb6e)

> `proxy` 是没问题的，我开着 `Clash`, 可以正常访问 Google

```
updater.exe --action=update --proxy=http://127.0.0.1:10808

升级中，请稍等

[1/9] new updater
[2/9] check whether need update
[3/9] download latest version
[4/9] unzip file
[5/9] adjust files
[6/9] adjust updater.exe
[7/9] remove old dir

panic: remove D:\Program Files\Typora\resources\plugin\_obgnail__typora_plugin.url: Access is denied.
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:419: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:579: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:610: 

goroutine 1 [running]:
main.main()
	D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:610 +0x26d
```

> 我又手动才成功

![image](https://github.com/obgnail/typora_plugin/assets/16939388/1509cf7e-8504-43b2-ab0b-574af5e61fb8)


> 可以成功了， Typora 也正常显示图片了，谢谢 dalao

![image](https://github.com/obgnail/typora_plugin/assets/16939388/36b1fdb4-c5d7-485e-b630-ff9b0764abcc)
![image](https://github.com/obgnail/typora_plugin/assets/16939388/548df7c8-f01d-46ad-ba3c-1fc6d770315f)

**Comment by obgnail** [comment]
@yiyungent 

windows 的权限管理太傻逼了。

既然如此，我建议你把自动更新关了吧。
因为它停在了 第七步 `[7/9] remove old dir`，第八步 `sync dir` 又没有执行，我怕把插件文件删了……

```toml
# 给 custom_plugin.user.toml 添加上下面的配置
[pluginUpdater]
[pluginUpdater.config]
auto_update = false
```
