### ISSUE TITLE
[feature request] 能不能添加对 Callouts 语法的支持

### ISSUE THREAD

**Issue by alfoil** [obgnail/typora_plugin#203]
如题，能不能添加对 Callouts 语法的支持？可以参考 Obsidian 的语法和渲染效果：https://help.obsidian.md/Editing+and+formatting/Callouts

**Comment by obgnail** [comment]
@alfoil 

新版本已经实现。麻烦试用看看。

**Comment by obgnail** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/48992887/7b997e8b-abac-4050-b3fd-e77e29da9d7c)

数量、类型、颜色、icon 皆可自己定义，请前往配置文件修改：
```toml
[[callouts.config.list]]
type = "note"
background_color = "#e1d1eb"
left_line_color = "#6a1b9a"
icon = "\\f040"
```
