### ISSUE TITLE
【建议】导出为HTML文件时可否保留echarts图表？

### ISSUE THREAD

**Issue by BrazilAmando** [obgnail/typora_plugin#216]
导出为HTML文件后，看板、时间线等功能完美保留，但echarts图表却为空，查看源码似乎没有包括echarts相关代码，不知是否可实现导出为html文件后echarts图表仍然能正常显示？谢谢！

**Comment by BrazilAmando** [comment]
提出该需求的主要原因是大部分同事未安装typora，直接将md文件发过去打开不具有通用性，写的酷炫的echarts图表成了孤芳自赏了，若发个html文件或自建个服务器远程访问较为方便。

**Comment by obgnail** [comment]
@BrazilAmando 

fixed。

注意配置：
```toml
# 渲染器: canvas/svg
# 怎么选择请参考：https://echarts.apache.org/handbook/zh/best-practices/canvas-vs-svg/
RENDERER = "svg"
# 导出时 echarts 转成什么格式
# 可选 png, jpg, svg
# 注意：png, jpg 只有在 canvas 渲染器的时候可用，svg 只有在使用 svg 渲染器的时候可用
 EXPORT_TYPE = "svg"
```
