### ISSUE TITLE
【auto_number】图片名字体是否能随主题字体

### ISSUE THREAD

**Issue by shanshilaoseng** [obgnail/typora_plugin#227]
【auto_number】图片名字体当前是默认宋体，是否能随主题字体

**Comment by obgnail** [comment]
@shanshilaoseng 

fixed. 添加了两个配置，要想跟随主题，可以设置为 inherit 或者你使用的字体。

```toml
# 编号的下标使用的字体
FONT_FAMILY = "monospace"
# 编号的下标的位置：left/right/center
ALIGN = "center"
```
