### ISSUE TITLE
[fix:升级bug] 自动升级,最新升级报错.

### ISSUE THREAD

**Issue by pro911** [obgnail/typora_plugin#240]
![image](https://github.com/obgnail/typora_plugin/assets/28957658/4c86ce2d-cfa4-458c-9fe7-d5ed248351b4)

**Comment by pro911** [comment]
```
升级中，请稍等

[1/9] new updater
[2/9] check whether need update
get latest version error: error status code: 403

It is already the latest version. Do not need update.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xec23e4]

goroutine 1 [running]:
main.update({0xc0000aa088?, 0xc0000d6010?}, 0xc0000acbd0?)
	D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:563 +0x304
main.main()
	D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:604 +0x1cf
```

**Comment by obgnail** [comment]
@pro911 你好，感谢反馈。

请问之前正常升级过吗？如果之前升级过，麻烦稍等一段时间后重新试一下。

似乎是拉取 github 的时候网络异常，报 403 了。我这边是可以正常升级的。

**Comment by obgnail** [comment]
@pro911 

怎么好的？重新执行就好了？还是手动下载的？

**Comment by obgnail** [comment]
@pro911 

其实很久之前就已经开启默认自动更新了，会在每次打开 Typora 五分钟后自动检测更新。不需要手动执行更新。

当然，如果你不希望自动更新，可以关闭：
```toml
[pluginUpdater.config]
# 打开Typora时自动静默升级（若为false，则start_update_interval、auto_exec_show配置失效）
auto_update = true
# 打开Typora多长时间后，开始执行升级流程（单位：ms）
start_update_interval = 300000 # (1000 * 60 * 5)
```
