### ISSUE TITLE
文字上色功能

### ISSUE THREAD

**Issue by jimmy123j** [obgnail/typora_plugin#254]
希望可以直接新增 Color Panel 針對 Color 與 Background-Color 進行控制，不需要透過 Html Source Code 進行

**Comment by obgnail** [comment]
@jimmy123j 

这该咋实现呀？

Typora 本质是操作 md 文件，要想颜色持久化，必然需要添加 html，所以你的需求是通过 Color Panel 一键添加 html？或者有现成的方案可以参考？

**Comment by obgnail** [comment]
@jimmy123j 

你好，新增了【text_stylize】插件，当前可以控制 color。可以试用看看。

**Comment by jimmy123j** [comment]
使用上沒問題，有 3 個建議

1. 新增 Closs Button，目前似乎需要再透過右鍵點選文字風格化才會關閉 Color Panel
2. 建議反黑點選顏色就能直接針對反黑文字套用顏色，目前看來要先按顏色產生 font tag，並在 tag 中輸入才會有效
對於沒有 html 編碼經驗的人來說會不知道如何使用
3. 因為作者將此功能稱為風格化，一開始以為有其他功能，但目前看起來僅先支援 Color
或許有機會可以拓展功能 font 相關功能例如整合高亮 background-color、fomt-family、border、letter width 等等 css，達到真正的「風格化」

感謝作者新增此功能，很實用，謝謝

**Comment by obgnail** [comment]
@jimmy123j 

感谢反馈。

确实，取名为「风格化」是有这个意图，此插件还处于起步阶段（所以您的反馈很重要），后续会做成类似于 editing toolbar 的东西，不过现在我比较忙，开发进度确实比较慢。

就目前插件现状，回复如下：

1. 配置文件中提供了两个快捷键 SHOW_MODAL_HOTKEY，SET_COLOR_HOTKEY，分别对应【弹出颜色面板】和【设置字体颜色】（颜色默认为最后一次的颜色），如果有需要可以修改。或者也可以使用【quickButton】插件，在右下角添加一个快捷按钮。（比如下图，我个人就添加了两个按钮）
2. ctrl+drag 可拖动
3. 也可以先选中文字，然后再点击按钮，如此，选中的文字就会自动加入 html（在我的想法中，应该是选中后，直接使用 SET_COLOR_HOTKEY 快捷键）

---
插件的配置：

```toml
[text_stylize]
# 启用插件
ENABLE = true
# 在右键菜单中展示的名称
NAME = "文字风格化"
# 是否在右键菜单中可点击
CLICKABLE = true
# 弹出颜色面板的快捷键
SHOW_MODAL_HOTKEY = ""
# 设置字体颜色的快捷键
SET_COLOR_HOTKEY = ""
# 每13个颜色一行
NUM_PER_LINE = 13
# 颜色列表（由于markdown支持的html语法限制， 不支持rgb格式的颜色）
COLORS = [
    "#330000", "#331900", "#333300", "#193300", "#003300", "#003319", "#003333", "#001933", "#000033", "#190033", "#330033", "#330019", "#000000",
    "#660000", "#663300", "#666600", "#336600", "#006600", "#006633", "#006666", "#003366", "#000066", "#330066", "#660066", "#660033", "#202020",
    "#990000", "#994C00", "#999900", "#4C9900", "#009900", "#00994C", "#009999", "#004C99", "#000099", "#4C0099", "#990099", "#99004C", "#404040",
    "#CC0000", "#CC6600", "#CCCC00", "#66CC00", "#00CC00", "#00CC66", "#00CCCC", "#0066CC", "#0000CC", "#6600CC", "#CC00CC", "#CC0066", "#606060",
    "#FF0000", "#FF8000", "#FFFF00", "#80FF00", "#00FF00", "#00FF80", "#00FFFF", "#0080FF", "#0000FF", "#7F00FF", "#FF00FF", "#FF007F", "#808080",
    "#FF3333", "#FF9933", "#FFFF33", "#99FF33", "#33FF33", "#33FF99", "#33FFFF", "#3399FF", "#3333FF", "#9933FF", "#FF33FF", "#FF3399", "#A0A0A0",
    "#FF6666", "#FFB266", "#FFFF66", "#B2FF66", "#66FF66", "#66FFB2", "#66FFFF", "#66B2FF", "#6666FF", "#B266FF", "#FF66FF", "#FF66B2", "#C0C0C0",
    "#FF9999", "#FFCC99", "#FFFF99", "#CCFF99", "#99FF99", "#99FFCC", "#99FFFF", "#99CCFF", "#9999FF", "#CC99FF", "#FF99FF", "#FF99CC", "#E0E0E0",
    "#FFCCCC", "#FFE5CC", "#FFFFCC", "#E5FFCC", "#CCFFCC", "#CCFFE5", "#CCFFFF", "#CCE5FF", "#CCCCFF", "#E5CCFF", "#FFCCFF", "#FFCCE5", "#FFFFFF",
]
```

> 具体修改配置，请阅读 `./plugin/global/settings/请读我.md`

---
如果你想使用【quickButton】，可以使用如下配置：

```toml
[quickButton]
# 右键菜单中展示的名称
name = "快速按钮"
# 是否启用此自定义插件
enable = true
# 插件配置
[quickButton.config]
# 添加的按钮
#   action：取个名字，不可重名
#   coordinate：往上为x正方向，往左为y正方向。(0,0) (0,1) (1,0) (1,1) 四个坐标已被其他插件占用
#   icon：icon class
#   font_size：控制icon大小
#   hint：提示信息
#   callback：回调函数
[[quickButton.config.buttons]]
action = "text_stylize_set_color"
coordinate = [2, 1]
icon = "fa fa-indent"
font_size = "17px"
hint = "弹出颜色面板"
callback = "text_stylize.call"
[[quickButton.config.buttons]]
action = "text_stylize_show_modal"
coordinate = [2, 0]
icon = "fa fa-home"
font_size = "20px"
hint = "设置字体颜色"
callback = "text_stylize.setColor"
```

> 当然，更深入使用 quickButton，需要您有 javascript 基础

---


![temp (1)](https://github.com/obgnail/typora_plugin/assets/48992887/b17dfa84-6b16-47ba-82a7-21ef1737c935)

**Comment by jimmy123j** [comment]
@obgnail 感謝作者回覆

真詭異，因為一開始嘗試的時候的確無法針對反黑的文字直接進行變色，但剛剛測試可以了

1. Close Button 的部分還是會建議，因為大多數人依舊是使用鼠標操作，不太會去記憶 Hotkey
2. 另外 Hover 的部分我自己是改成使用 box-shadow 的 inset，比較不會因為 Boder 放大至 2px 而導致 color tr 位移

Toolbar 是很好的想法，期待後續作者後續完善功能

![Test](https://github.com/obgnail/typora_plugin/assets/46530155/7655d68d-995f-49e7-95e2-cf8d4a0a82af)

**Comment by pengxiandyou** [comment]
感谢提出此建议和作者实现。要是没找到这个插件，我还要学习自己去实现一个简单的，那有点难

**Comment by chenchunlai** [comment]
@jimmy123j  @obgnail 右键打开【文字风格化】以后，是否遇到 颜色选择对话框 关不掉的情况？

我尝试了 按 ESC 键以及在别的地方单击或者双击，它都没有退出

下面是一些信息：
typora版本：1.7.6
插件版本：1.6.20

**Comment by obgnail** [comment]
@chenchunlai 

text_stylize 插件还很粗糙。还在起步阶段，只是实现了基本功能。

目前有两种退出方式：
- 右键菜单 -> 文字风格化（怎么来的，就怎么退出）
- 快捷键，具体可以看下面配置

```toml
[text_stylize]
# 弹出颜色面板的快捷键（第一次弹出面板，第二次退出面板）
SHOW_MODAL_HOTKEY = ""
# 设置字体颜色的快捷键
SET_COLOR_HOTKEY = ""
```

**Comment by chenchunlai** [comment]
> @jimmy123j @obgnail 右键打开【文字风格化】以后，是否遇到 颜色选择对话框 关不掉的情况？
> 
> 我尝试了 按 ESC 键以及在别的地方单击或者双击，它都没有退出
> 
> 下面是一些信息： typora版本：1.7.6🔄  ❓ 插件版本：1.6.20

我明白了 它需要右键选择 【文字风格化】才能再次关闭，但似乎它可以被优化，在完成给文字上色以后，按ESC键就可以关闭掉

**Comment by obgnail** [comment]
@jimmy123j @pengxiandyou @chenchunlai 

这个插件出乎我意料的受欢迎。时隔两个月，我花了点时间，为其做了全面升级。

现在这个插件应该可以称为真正的【风格化】了。

![text_stylize](https://github.com/obgnail/typora_plugin/assets/48992887/6baea993-3301-4a50-8f17-ba1b823b6326)

**Comment by obgnail** [comment]
新增如下配置，现在用户可以：
1. 自定义工具栏上的所有按钮
2. 为任意一个功能绑定任意一个快捷键

```toml
# 工具栏的按钮:
#   - weight:                加粗
#   - italic:                斜体
#   - underline:             下划线
#   - throughline:           中划线
#   - overline:              上划线
#   - superScript:           上标
#   - subScript:             下标
#   - emphasis:              强调符号
#   - title:                 标题尺寸
#   - increaseSize:          增大尺寸
#   - decreaseSize:          减小尺寸
#   - increaseLetterSpacing: 增大间隙
#   - decreaseLetterSpacing: 减小间隙
#   - family:                字体
#   - foregroundColor:       前景色
#   - backgroundColor:       背景色
#   - borderColor:           边框
#   - erase:                 移除格式
#   - blank:                 无功能，用于占位
#   - setBrush:              设置格式刷
#   - useBrush:              使用格式刷
#   - move:                  移动工具栏
#   - close:                 关闭工具栏
TOOLBAR = [
    "weight", "italic", "underline", "throughline", "overline", "title", "superScript", "subScript",
    "emphasis", "increaseLetterSpacing", "decreaseLetterSpacing", "increaseSize", "decreaseSize", "family",
    "foregroundColor", "backgroundColor", "borderColor", "setBrush", "useBrush", "erase", "blank", "move", "close"
]

# 设置样式的快捷键
#   1. hotkey: 快捷键
#   2. action: 上述的工具栏按钮
ACTION_HOTKEYS = [
    { hotkey = "", action = "foregroundColor" },
    { hotkey = "", action = "backgroundColor" },
]

# 默认颜色
DEFAULT_COLORS = { FOREGROUND = "#330000", BACKGROUND = "#FFFFFF", BORDER = "#330000" }
```
