### ISSUE TITLE
兼容obsidian的基于库根目录的绝对路径

### ISSUE THREAD

**Issue by calmwaves111** [obgnail/typora_plugin#259]
首先十分感谢您为typora开发插件，您第一次在小众软件上发布我就知道了，没想到您能坚持更新这么长时间，为typora增加了这么多的功能
看起来您也是知道obsidian的，我在使用obsidian时对于所有的链接都使用的是【基于库根目录的绝对路径】，但是typora里显示不出来图片或者跳转到对应文件
typora有一个yaml设定可以实现这种功能（并且之前它这个功能有点问题，最近才修好了 https://github.com/typora/typora-issues/issues/5672 
```
---
typora-root-url:
---
```
但是这个要在每一篇开头都加上这个yaml，很麻烦

我希望能有一个全局的设置 https://github.com/typora/typora-issues/issues/1573#issuecomment-629617515 ，直接让typora使用此种路径（甚至不兼容相对路径也没关系）

另外obsidian的【基于库根目录的绝对路径】也是有点问题的，它缺一个前导/ https://forum.obsidian.md/t/start-absolute-path-with-a-leading-slash/32501 ，vscode中无法正确显示图片，如果您对实现这个感兴趣，需要注意一下

再次感谢您的贡献

**Comment by obgnail** [comment]
@calmwaves111 

麻烦能详细说明一下你的使用场景吗？

看表述你似乎是主用 Obsidian，偶尔使用 Typora 打开文件，由于 Obsidian 的配置导致 Typora 图片链接有问题？

**Comment by calmwaves111** [comment]
是的没错，我主要使用obsidian来管理我的md笔记，但是obsidian的编辑器不如typora，所以我偶尔会用typora打开文件

我在ob中的设置是这样的
![image](https://github.com/samuele-cozzi/obsidian-marp-slides/assets/56907077/b0987a87-caf7-449d-a0de-39fac43d6591)

我的库文件夹路径是`E:\obvault\obsidianfold`
以下面的文件结构为例
- obsidianfold（vault）
	- Afolder
	- Bfolder
		- assets
			- example.png
		- test.md
	- Cfolder

in `test.md`，`example.png`通过下面的链接引入
```
![example.png](Bfolder/assets/example.png)
```
这张图片无法在typora中显示出来

**Comment by obgnail** [comment]
@calmwaves111 你好，1.6.16 版本已经支持此功能。

因为这个需求比较个性化，需要您手动开启此功能。

配置如下：
```toml
############### redirectLocalRootUrl ###############
[redirectLocalRootUrl]
# 右键菜单中展示的名称
name = "替换本地资源根目录"
# 是否启用此自定义插件
# 由于typora本身的bug，此插件仅在typora1.7.5及以后才可用（参考：https://github.com/typora/typora-issues/issues/5672）
# 【metaNode的typora-root-url参数】的优先级大于【此插件】。也就是说，若文件显式设置了typora-root-url，那么此插件在该文件失效。
enable = false
# 是否在右键菜单中隐藏
hide = true
# 插件配置
[redirectLocalRootUrl.config]
# 根目录，支持绝对路径(如D:\tmp\img)和相对路径(如.\assets)，填写时请注意转义反斜线（若为空，则此插件失效）
root = "./"
# 过滤的正则表达式：只有文件名命中filter_regex匹配的文件才使用此插件（若为空，则全部文件都使用此插件）
filter_regexp = ""
```
