### ISSUE TITLE
需求：能否改善Typora的链接功能

### ISSUE THREAD

**Issue by Bronya-Rayi** [obgnail/typora_plugin#262]
Typora中，只能通过`[跳转](#跳转一级标题)`的格式实现在本页内的链接跳转，或者使用`[跳转](C:/Develop/Docs/Readme1.md)`的格式实现新开窗口跳转其他文档
目前无法通过类似`[跳转](C:/Develop/Docs/Readme1.md#跳转一级标题)`的格式跳转至其他文档的指定锚点
不知是否可以通过插件的形式实现简单的单向链接，如果能实现双向链接的功能就更完美了

**Comment by obgnail** [comment]
Typora 在 1.1 版本就支持这个功能了。

并且在这个 [issue](https://github.com/obgnail/typora_plugin/issues/147) 后，window_tab 已经兼容这种情况了：

```toml
############### window_tab ###############
[window_tab]
# typora1.1版本以后，支持使用锚点跳转到本地文件，是否拦截处理（从新建窗口改成新建标签页）
INTERCEPT_INTERNAL_AND_LOCAL_LINKS = true
```
---

你可以尝试使用一下：

target.md：
```
## this-is-a-title
<a id="anchor"></a> Anchor
```

reference.md：
```
[text](./target.md#this-is-a-title)
[text](./target.md#anchor)
```

---

reference:
- [Typora1.1更新文档](https://support.typora.io/zh/What's-New-1.1/#%E6%96%87%E4%BB%B6%E9%93%BE%E6%8E%A5)
- [内部链接使用说明](https://support.typora.io/Links/#internal-links)
