### ISSUE TITLE
[bug]启用1.5.14版本的插件之后，使用ctrl+shift+k插入代码块的快捷键失效。

### ISSUE THREAD

**Issue by liufeiyafly** [obgnail/typora_plugin#269]
系统版本：Windows 10 专业版22H2
Typora版本：1.2.4

**Comment by obgnail** [comment]
@liufeiyafly 

这其实是一个历史遗留问题。

因为我开发【中英文混排优化】这个插件的时候，分配的快捷键就是 ctrl+shift+k，那时 Typora 还没有使用此快捷键。

解决方案：修改配置文件，将下面 HOTKEY 选项改成 HOTKEY = ["ctrl+shift+b"]

> 具体怎么修改，请参考 `plugin\global\settings\请读我.md`

晚上我会上线一个版本，去掉此快捷键，如果不想手动修改，你也可以等明天再来。

```toml
############### md_padding ###############
[md_padding]
# 启用插件
ENABLE = true
# 在右键菜单中展示的名称
NAME = "中英文混排优化"
# 是否在右键菜单中可点击
CLICKABLE = true
# 快捷键
# 由于新版本Typora占用了ctrl+shift+k快捷键，所以ctrl+shift+k可能会失效
HOTKEY = ["ctrl+shift+k", "ctrl+shift+b"]
# 不希望拆分的单词：
#   == 是github markdown的高亮拓展语法
IGNORE_WORDS = ["=="]

```
