### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Liu8Can** [obgnail/typora_plugin#272]
有没有插件整体的开启和关闭功能

**Comment by obgnail** [comment]
配置文件的【global】有 ENABLE 选项

```toml
############### global ###############
# 通用配置
[global]
# 所有插件的开关，若设为false，则关闭全部插件
ENABLE = true
```

配置文件夹位置：/plugin/global/settings/

具体怎么修改请阅读 /plugin/global/settings/请读我.md
