### ISSUE TITLE
关于章节折叠的一点建议

### ISSUE THREAD

**Issue by BinaryQ** [obgnail/typora_plugin#315]
无法一键递归展开单个标题。建议新增个快捷键可以一键展开选中标题等级下的所有折叠。例如选中一个`h2`标题，这展开这个标题下所有章节（h2-h6）。

**Comment by obgnail** [comment]
@BinaryQ 你好，感谢反馈。

已经实现，今天晚些发版。

> 注意：我并没有默认为此功能设置修饰键，需要你手动修改 `collapse_paragraph.MODIFIER_KEY.COLLAPSE_RECURSIVE ` 配置。具体如何修改配置，请参考 [请读我.md](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md)

新增如下配置：
```toml
[collapse_paragraph]
# 严格模式：只当点击到h1~h6时，才触发折叠/展开。若为false，则自动向上寻找最近的h1~h6
STRICT_MODE = false

# 各个功能对应的修饰键
# 1.支持ctrl/alt/shift的随意组合（如"shift+alt"，"ctrl+shift"）
# 2.但是不能为"alt"（因为alt+click已经被【scrollBookmarker】插件占用），也不能为"shift"（因为shift+click被系统自带的【框选】功能占用）
# 3.若为空，表示不启用此功能
# 4.举例：【COLLAPSE_SIBLINGS = "ctrl+alt"】：当用户同时按住键盘ctrl和alt，并且鼠标click标题时，折叠/展开父章节下所有同级的章节
[collapse_paragraph.MODIFIER_KEY]
# 折叠/展开 单个章节
COLLAPSE_SINGLE = "ctrl"
# 折叠/展开 父章节下所有同级的章节
COLLAPSE_SIBLINGS = "ctrl+alt"
# 折叠/展开 当前文件所有同级的章节
COLLAPSE_ALL_SIBLINGS = "ctrl+shift+alt"
# 递归折叠/展开 当前章节
COLLAPSE_RECURSIVE = ""
```
