### ISSUE TITLE
关于markmap的一点建议

### ISSUE THREAD

**Issue by BinaryQ** [obgnail/typora_plugin#316]
1. 弹窗形式的`markmap`可以点击分支跳转到对应章节。
2. 插入`markmap`块时，希望可以直接插入弹窗预览时（当前文件markmap）的内容，而不是模板内容。插入模板内容的右键菜单其实可以保留，再新增个插入当前文件的`markmap`菜单就完美了。

插件做的很棒，很喜欢，也在跟身边的朋友极力推荐。加油！

**Comment by obgnail** [comment]
@BinaryQ 

你好，感谢反馈。
两个需求已实现，今天晚些发版。

**Comment by obgnail** [comment]
新增了 CLICK_TO_LOCALE  配置选项

```toml
[markmap]
# 点击markmap节点，定位到文档位置（跳转到对应章节）
CLICK_TO_LOCALE = true
```
