### ISSUE TITLE
键入<br>分行后显示line rule description

### ISSUE THREAD

**Issue by Guohairui6** [obgnail/typora_plugin#323]
键入<br>分行符，line rule description显示
12    MD033  Inline HTML,
13    MD033  Inline HTML,
14    MD033  Inline HTML
请问如何消除，或者如何关闭line rule description功能，看的我难受
![Snipaste_2023-11-28_11-52-29](https://github.com/obgnail/typora_plugin/assets/135523508/cedcc321-8e0d-4812-ba0a-1d03e9f77b1e)

**Comment by obgnail** [comment]
@Guohairui6 你好，感谢反馈。

如果你是想禁用 markdownLint 功能，再次点击右上角的小方块即可。
![Snipaste_2023-11-28_12-03-39](https://github.com/obgnail/typora_plugin/assets/48992887/2d20c5f6-0e75-4c47-99ff-abed1964e04d)


---


如果你是想禁用 MD033 的规则检测，可以修改配置文件

```toml
[markdownLint]
[markdownLint.config]
# 禁用的规则（参考：https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md）
disable_rules = ["MD012", "MD013", "MD041"]
```

给上面的 disable_rules 加上 MD033

> 具体如何修改配置文件，请参考[请读我.md](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md)

**Comment by obgnail** [comment]
@Guohairui6 如果你不想使用 markdownLint 功能，可以修改配置文件，禁用此插件

```toml
[markdownLint]
# 是否启用此自定义插件
enable = true
```

将上面的 enable 改为 false
