### ISSUE TITLE
"line  rule   description"窗口似乎是固定尺寸，能否修改为根据窗口自适应。

### ISSUE THREAD

**Issue by Guohairui6** [obgnail/typora_plugin#327]
如题，
![image](https://github.com/obgnail/typora_plugin/assets/135523508/48f7a2eb-5b0e-40ef-902c-78547d86edca)
![Uploading image.png…]()

**Comment by Guohairui6** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/135523508/9afd9543-ae45-4ae8-8495-e73370631370)
当窗口过小的时候，显示不完整且无法找到右上角的小方块

**Comment by obgnail** [comment]
@Guohairui6 你好，感谢反馈。

1. 本项目的所有的弹窗，基本都是可以 ctrl+鼠标拖拽 来移动弹窗的。
2. 弹窗太大覆盖小方块的问题也会处理。有进度的话我会在下面留言。
3. 你提了个重复的 issue，我把另一个关了，后续进度在这里留言。

**Comment by obgnail** [comment]
@Guohairui6 

新版本已经支持上述需求。

新增配置如下

```toml
[markdownLint]
[markdownLint.config]
# 将检测规则的案文翻译为中文
 translate = true
# 弹窗的宽度
#   1. auto:  根据文字自适应
#   2. 500px: 500 像素（不一定是 500，可以任何正整数）
modal_width = "auto"
# 弹窗的最大高度
 modal_max_height = "500px"
# 弹窗的字体大小
 modal_font_size = "13px"
```
