### ISSUE TITLE
file_counter在点击某个子文件时失效

### ISSUE THREAD

**Issue by pengber** [obgnail/typora_plugin#328]
![Video_20231129162849](https://github.com/obgnail/typora_plugin/assets/58100402/d079ccfa-feeb-4ee8-8eee-102c05fb7d23)

点击前两个子文件没问题, 点击第三个子文件文件数不再显示

**Comment by obgnail** [comment]
@pengber 你好，感谢反馈。

其实是文件名太长被顶到右边去了。你拉动一下横向滚动条就能看到了。

如果你仔细查看配置文件，是可以使用 ctrl + wheel 滚动横向滚动条的
```toml
[file_counter]
# 当侧边栏出现横向滚动条时，允许ctrl+wheel进行横向滚动
CTRL_WHEEL_TO_SCROLL_SIDEBAR_MENU = true
```

![Snipaste_2023-11-29_16-38-55](https://github.com/obgnail/typora_plugin/assets/48992887/70f4b714-2df5-471e-93dc-00efd1d80e28)
![Snipaste_2023-11-29_16-39-04](https://github.com/obgnail/typora_plugin/assets/48992887/7a27ad2b-fa39-4c7d-9e3e-34b7a61db412)
