### ISSUE TITLE
【功能建议或小问题】选中添加引号问题

### ISSUE THREAD

**Issue by pengxiandyou** [obgnail/typora_plugin#331]
以双引号为例。
输入法：微软拼音、华宇拼音
Typora1.4.4 x64
1. 英文情况下，对选中的文字可使用双引号直接包裹住；
2. （问题）中文状态下，对选中的文字使用双引号则是替换。

不知能否实现中英文的符号都可直接包裹

3.（问题）中文状态下，输入一次引号后自动可自动匹配。当光标移动出引号外时，再输入引号则是右引号。

不知能否实现向前扫描固定字符数来判断此次输入的引号是左引号（保留自动匹配）还是右引号。

**Comment by obgnail** [comment]
@pengxiandyou 

你好，第一个需求已支持，今天或明天发版

添加了配置：
```toml
[chineseSymbolAutoPairer]
# 当框选文字时，键入中文符号，自动包裹框选文字
auto_surround_pair = true
# 自动包裹框选文字后，自动框选文字
auto_select_after_surround = true
```

第二个需求，

我知道你想表达的问题，你觉得比较好的解决方案是什么？或者说那些比较出名的中文输入法是怎么做的？
