### ISSUE TITLE
血书请求Git同步功能

### ISSUE THREAD

**Issue by Chenmo1212** [obgnail/typora_plugin#335]
血书请求Git同步功能

**Comment by obgnail** [comment]
@Chenmo1212 你好，感谢反馈。

能说明一下具体的使用场景吗？

**Comment by obgnail** [comment]
@Chenmo1212 

您好，能说明一下具体的使用场景吗？

**Comment by xfh090486** [comment]
家里和公司还有其他电脑好几个，能尽量简单的自动同步文件最好。

**Comment by obgnail** [comment]
@xfh090486 你好，感谢反馈。

通过 git 实现自动同步不现实呀。

git 本身不是增量式推送修改的，而是全量式的（稍微修改文件，就要推送一整个文件）

实现这样的需求，就面临如下问题：
- 在推送方：一旦检测到文件变动，就要推一次全量的文件，一天能给你干到上千个 commits。git 仓库马上就爆炸了。
- 在接收方：每隔几秒就要 git pull 一次，也很吃资源。

---

比较现实的方案，有两种：

## 使用 git 手动同步
可以使用 commander 插件

![Snipaste_2023-12-11_12-11-23](https://github.com/obgnail/typora_plugin/assets/48992887/4d6f2f7b-1b39-45a4-ad25-dd809418fedf)

commander 是支持自定义命令并且支持为命令快捷键的。

比如，修改 commander 插件的 BUILTIN 配置，就可以使用 ctrl+alt+c 推送修改，使用 ctrl+alt+p 获取最新版本
```toml
[[commander.BUILTIN]]
name = "GitCommit"
hotkey = "ctrl+alt+c"
shell = "cmd/bash"
cmd = 'cd $m && git add . && git commit -m "message"'
[[commander.BUILTIN]]
name = "GitPull"
hotkey = "ctrl+alt+p"
shell = "cmd/bash"
cmd = 'cd $m && git pull origin master'
```

## 最现实的方案：使用同步网盘

这也是我采用的方案，我使用的是 dropbox，在淘宝花 5 块钱买个扩容服务（你要是不嫌烦也可以自己扩容，花费0元），就可以有 18.48 G 的空间，对于 md 这种纯文本文件，18.48 G 应该是够用的。

使用同步网盘最大的好处就是：安全、无感知。

我现在也是多台电脑同步用的，Typora 开启自动保存功能后，不需要任何额外的操作。

白天在公司电脑写的文件，晚上家里的电脑就可以直接使用，省心多了。
