### ISSUE TITLE
【feat request】一键为 没有设置语言的代码块 添加语言

### ISSUE THREAD

**Issue by obgnail** [obgnail/typora_plugin#342]

**Comment by obgnail** [comment]
ref: https://github.com/obgnail/typora_plugin/issues/340

**Comment by obgnail** [comment]
已实现，代码在 dev。

**Comment by obgnail** [comment]
由于此功能有风险（需要一次性将全部的代码块都加载出来，如果这个文件很大，代码块很多，这可能会导致 Typora 在 N 秒内失去响应，并且短时间内存飙升），所以默认关闭，需要用户手动开启 ENABLE_DANGEROUS_FEATURES 选项。

```toml
[fence_enhance]
# 在右键菜单中启用危险的功能
#   危险功能：此功能会消耗巨量资源并导致Typora长时间（几秒到几十秒）失去响应
ENABLE_DANGEROUS_FEATURES = false
```

![Snipaste_2023-12-30_17-58-45](https://github.com/obgnail/typora_plugin/assets/48992887/355d82c2-09e3-4844-9ce7-7161e5f6b0ef)
