### ISSUE TITLE
【功能建议：对 latex 内联语法中英文混排】

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#345]
# 偶然想法
用 中英文混排优化 插件的时候偶然的一个想法，可不可以将 Latex 内联语法也来一个混排优化咧？

# 演示例子
```
“假设有一个数$X_{2}$为给定值...”
```
变成：
```
“假设有一个数 $X_{2}$ 为给定值...”
```

**Comment by obgnail** [comment]
@xiaogithubooo 

本来就支持呀 

![temp](https://github.com/obgnail/typora_plugin/assets/48992887/16acd718-84c8-4e15-861e-9e78f179137e)

**Comment by xiaogithubooo** [comment]
我刚刚回去看了一下，确实支持，但是好像是在有些时候不支持，好像在无序列表语法里的 latex 就不会插入空格，但是有些地方就会

https://github.com/obgnail/typora_plugin/assets/113878415/30d27b09-1bbf-4ddd-9029-75b5cf740251

**Comment by xiaogithubooo** [comment]
下面的 latex 就生效了（在注释框里的 Latex），但是在无序列表里的就没有生效（不会是我主题的问题吧...😯？）

**Comment by obgnail** [comment]
@xiaogithubooo 

我不太懂 latex，麻烦能把有问题的文本发出来吗？

 中英文混排优化 插件是基于 markdown 抽象语法树实现的，可能对 latex 的支持不太好

**Comment by xiaogithubooo** [comment]
这个文件是一段测试文本，我这边又试了一下，插件在其他地方都生效，就是在无序列表不生效

https://github.com/obgnail/typora_plugin/assets/113878415/e244322b-8bb3-4fcc-a1ab-2eb4da90d445

[test.md](https://github.com/obgnail/typora_plugin/files/13660734/test.md)

**Comment by obgnail** [comment]
神奇😂

我明天看有没有时间处理一下。

话说你们都不爱用快捷键的吗，每次收到反馈的时候看大伙都不用

**Comment by xiaogithubooo** [comment]
这也不知道是不是软件本身的问题，怪神奇的hhhhh。
快捷键的话用的频率还行，主要是视频里我想完整演示出来，直接用快捷键不好看出效果😏

**Comment by ljacksonl** [comment]
> 神奇😂
> 
> 我明天看有没有时间处理一下。
> 
> 话说你们都不爱用快捷键的吗，每次收到反馈的时候看大伙都不用

所有的插件都支持快捷键吗，我看快捷中心里面只有一小部分快捷键

**Comment by obgnail** [comment]
@ljacksonl 

先说结论：**你可以为任何逻辑、任何代码、任何功能绑定任何快捷键**。

在本项目中，快捷键分成两种，一种是预设的快捷键，一种是自定义的快捷键。

## 预设的快捷键

预设的快捷键是用户常用功能绑定的快捷键，他们分布在 settings.defualt.toml 和 custom_plugin.default.toml 中，其**特点是都带 hotkey 关键字**，比如：

```toml
# settings.defualt.toml
[search_multi]
HOTKEY = "ctrl+shift+p"  # 快捷键的字符串统一采用 【ctrl/shift/alt+字母】 的形式

[commander]
HOTKEY = "ctrl+g"        # 快捷键的字符串统一采用 【ctrl/shift/alt+字母】 的形式
```
```toml
# custom_plugin.default.toml 
[templater]
[templater.config]
hotkey = ""   # 这里为空，意思就是没有为其设置快快捷键

[darkMode]
[darkMode.config]
# 快捷键
hotkey = ""  # 这里为空，意思就是没有为其设置快快捷键
```

## 自定义的快捷键

自定义的快捷键，就是**为任何你想要的函数绑定快捷键**。这个函数可以是系统自带的，也可以用户自己写的。也就是说，如果上面预设的快捷键没有你想要的，你可以在这里配置。

自定义快捷键这个功能，需要您有基础的 JavaScript 基础（我刚刚看了一下您的 repo，有 JavaScript 的，所以您应该是没问题的）。

要想使用此功能，需要您
1. 启用 【hotkeyHub】插件（默认是开启的，除非您手动禁用过此插件，否则可以忽视）
2. 修改 hotkey.user.toml 文件

> 具体如何修改，您可以看一下 hotkey.default.toml 文件，里面有详细说明
