### ISSUE TITLE
文字风格化优化

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#347]
是否可以再考虑在右下角中加入类似word这种交互方式
![image](https://github.com/obgnail/typora_plugin/assets/26114336/3f8b1ccd-9a70-49db-a61c-1d7882272cb6)

![image](https://github.com/obgnail/typora_plugin/assets/26114336/360359fa-86b3-4535-a99b-f52e69e0bda0)

**Comment by SnowMaples** [comment]
引申出提供类似word方式的加粗，下划线，删除线这种文本格式工具栏。

**Comment by obgnail** [comment]
@SnowMaples 

有一个 quickButton 插件，支持自定义右下角的按钮。

尝试在 ./plugin/global/settings/custom_plugin.user.toml **新增**如下内容：
```toml
[quickButton]
enable = true
[quickButton.config]
[[quickButton.config.buttons]]
action = "text_stylize_button"
coordinate = [0, 2]
icon = "fa fa-pencil"
font_size = "17px"
hint = "文字风格化"
callback = "text_stylize.call"
```

> 只要你嫌乱，右下角的按钮你可以加到满屏幕都是。

其中各个参数的意思如下：
1. `action`: 取个名字，内容不做要求，但不可重名
2. `coordinate`: 按钮的坐标。往上为x正方向，往左为y正方向。(0,0) (0,1) (1,0) (1,1) (2,0) (2,1) 已被其他插件占用
3. `icon`: iconClass（所有的icon及其对应的iconClass请参考：https://www.adfwebmagazine.jp/wp-content/uploads/test_v4.1.pdf）
4. `font_size`: 控制icon大小
5. `hint`: 提示信息
6. `callback`: 回调函数

**Comment by obgnail** [comment]
如有问题，请在下面留言

**Comment by SnowMaples** [comment]
谢谢您这么详尽的回复，实践可行。
另外根据您的回复，按钮的坐标应该也是可以自定义的吧，我想调整一下按钮的分布，希望改成如下，不知是否可行。
![image](https://github.com/obgnail/typora_plugin/assets/26114336/cbb6b958-e7ad-49d6-9228-4b55e1423e51)

**Comment by SnowMaples** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/26114336/3831873b-47f3-4e95-98be-4dd98eb91f66)
新增的按钮按照您给的提示已经调整，默认的不知道怎么改。

**Comment by obgnail** [comment]
@SnowMaples 

## 这是个历史包袱😂

目前默认的按钮是不可配置的，因为它写死在代码中了。比如下面的一键到顶插件：
```js
class goTopPlugin extends BasePlugin {
    ...
    process = () => {
        if (this.config.USE_BUTTON) {
            const call_ = (ev, target, action) => this.call(action);
            this.utils.registerQuickButton("go-top", [1, 0], "到顶部", "fa fa-angle-up", null, call_);
            this.utils.registerQuickButton("go-bottom", [0, 0], "到底部", "fa fa-angle-down", null, call_);
        }
    }
    ...
}
```
---

## 为什么会出现这种情况？
答：quickButton 原本被设计成一个组件，后面才被提升一个插件。**被升级为插件时，已经有太多其他插件用到了这个功能**。并且这个插件被默认设置为禁用状态。

**我无数次想把默认的按钮改成可配置的形式**，但是 **会破坏用户的配置**，也就是会做破坏性更新。

极端情况下，某些不懂修改配置的小白用户会完全失去右下角的快捷按钮。

## 破坏性有多大？
假设我现在做了更新，您也更新了新的插件版本，那么您必须去 ./plugin/global/settings/custom_plugin.user.toml 文件，删除上述的内容，才能恢复原状。

否则您的 quickButton 也会处于不可用状态。

## 开发者提问
1. 您知道本系统存在配置文件吗？
2. 您知道怎么修改配置吗？今天之前您修改过配置吗？
3. 在我说出上面的恢复方案前，您能猜出/推理出恢复方法吗？
4. 您觉得这个更新要不要做？

**Comment by obgnail** [comment]
影响范围：【修改过配置，当没有完全理解配置参数含义】的用户

**Comment by SnowMaples** [comment]
感谢您的详细回复。

### 回复开发者提问：
1. 知道存在配置文件
2. 对toml语法不熟悉，在今天之前没改过配置。
3. 之前使用的五六个月前的版本，当时的多标签还存在遮挡首行的情况，没有updater.exe，这次升级1.7.9版本时采用的方式是直接删除Typora\resources\app\plugin文件夹下的所有文件，进行全覆盖更新。
4. 对我来说这个更新可以不做，目前的几个默认按钮都比较实用。不过鉴于您曾经无数次想把默认按钮改成可配置的情况（笑），我觉得还是要做更新。

### 自问自答：
#### 什么人会使用这个插件？
经常使用typora、对原生功能需要做一些增强的人才会来github中寻找typora插件。比如我非常需要多标签打开的功能才在github中寻找插件。
#### 什么人需要更新这个插件？
对当前使用的版本功能不满意（比如我对字体标红的快捷操作有一定需求，之前使用的版本没有），希望您增加或者优化一些功能。如果是迫切需要的功能，能通过github找到您这个插件的人是会在此提issue的，目前来看应该不多。
#### 如果做了这个更新，修改过配置却不理解如何恢复的人怎么办？
我看到您编写了一个updater.exe，能不能通过调整插件升级逻辑对用户的配置 ./plugin/global/settings/custom_plugin.user.toml 进行解析重写呢（我不知道这个工作量有多少，只是单纯提供一个思路（捂脸笑哭））

再次感谢您的严谨详细的回复。

**Comment by obgnail** [comment]
@SnowMaples 

做了一个违背祖宗的决定。我给 quickButton 做了不兼容升级。**现在支持快捷按钮的完全配置，用户将拥有全部的管理权限**。

当前配置如下：
```toml
[quickButton]
# 右键菜单中展示的名称
name = "快速按钮"
# 是否启用此自定义插件
enable = true
# 是否在右键菜单中隐藏
hide = true
# 在右键菜单中的出现顺序（越大越排到后面）
order = 1
# 插件配置
[quickButton.config]
# 添加的按钮
#   action:     取个名字。若不想取名请置为空；若取名则不可重名，建议使用不带空格的纯英文
#   disable:    禁用此按钮
#   coordinate: 坐标。往上为x轴正方向，往左为y轴正方向，从零开始计数。
#   icon:       icon css class。所有的 icon 及其对应的 css class 请参考：https://www.adfwebmagazine.jp/wp-content/uploads/test_v4.1.pdf
#   size:       控制icon大小
#   hint:       提示信息
#   callback:   回调函数。采用 pluginName.MethodName 的形式。
#               MethodName 请通过阅读源码查找。如果您不懂代码，但还是想添加按钮，有个碰运气技巧：在【右键菜单->常用插件->自定义插件下的插件】基本都是 XXX.callback，其余插件基本都是 XXX.call
buttons = [
    { action = "", disable = false, coordinate = [0, 0], hint = "直达底部", size = "28px", icon = "fa fa-angle-down", callback = "go_top.goBottom" },
    { action = "", disable = false, coordinate = [1, 0], hint = "直达顶部", size = "28px", icon = "fa fa-angle-up", callback = "go_top.goTop" },
    { action = "", disable = false, coordinate = [2, 0], hint = "夜间模式", size = "18px", icon = "fa fa-adjust", callback = "darkMode.callback" },
    { action = "", disable = false, coordinate = [3, 0], hint = "混排优化", size = "17px", icon = "fa fa-align-justify", callback = "md_padding.call" },
    { action = "", disable = false, coordinate = [0, 1], hint = "思维导图", size = "22px", icon = "fa fa-code-fork", callback = "markmap.onButtonClick" },
    { action = "", disable = false, coordinate = [1, 1], hint = "图片管理", size = "17px", icon = "fa fa-image", callback = "imageReviewer.callback" },
    { action = "", disable = false, coordinate = [2, 1], hint = "书签管理", size = "17px", icon = "fa fa-bookmark", callback = "scrollBookmarker.callback" },
    { action = "", disable = false, coordinate = [3, 1], hint = "高亮搜索", size = "17px", icon = "fa fa-search", callback = "search_multi.call" },
]
```
