### ISSUE TITLE
建议功能：浮动工具栏

### ISSUE THREAD

**Issue by PiscesDreamer** [obgnail/typora_plugin#353]
能否考虑将右下角的按钮收纳进类似iOS快捷浮动栏的形式，因为我发现自己有时候需要对md文件的内容截图的时候，右下角
的功能按钮总是会占据截图空间，如果有办法像下面这样能自定义地把一些功能放进悬浮球里面，需要的时候点击悬浮球去开启对应的功能，会很酷。

![image](https://github.com/obgnail/typora_plugin/assets/81842690/16e6dfb3-7be3-41c6-8ae7-a78fd6c6361e)

![image](https://github.com/obgnail/typora_plugin/assets/81842690/af814729-00dd-4482-be08-425140ff4c24)

**Comment by obgnail** [comment]
@PiscesDreamer 您好，感谢反馈。

> 首先说明一下，右下角的按钮，其实是通过 quickButton 这个插件实现的。所以您的需求是针对此插件的。

我总结了一下您的需求，您看对不对：

1. 按钮能隐藏或移动
2. 按钮功能支持自定义


## 按钮能隐藏或移动

您可以尝试鼠标右键 Typora_plugin 右下角的按钮，可以仅保留一个，隐藏其他的按钮（这个功能是在一两个月前加的，其实算是彩蛋，所以我没有详细说明）

![Snipaste_2023-12-17_20-51-22](https://github.com/obgnail/typora_plugin/assets/48992887/ca96ecc2-1a30-4019-80c2-086004e546db)

其实这就有点像 IOS 快捷浮动栏，至少也得保留一个悬浮球

还是说您是希望右下角的按钮支持像悬浮球一样拖动？


## 按钮功能支持自定义

看您的截图，您使用的 Typora_plugin 应该不是最新版本。

**最近版本的 plugin 可以通过修改配置，自定义按钮的数量、坐标、功能等等**

> 您可以看一下这个 [issue](https://github.com/obgnail/typora_plugin/issues/347)

举例，修改 quickButton 的 buttons 配置，为其添加八个按钮：

```toml
[quickButton]
# 添加的按钮
#   disable:    禁用此按钮
#   coordinate: 坐标。往上为x轴正方向，往左为y轴正方向，从零开始计数。
#   icon:       icon css class。所有的icon及其对应的css class，请参考：https://www.adfwebmagazine.jp/wp-content/uploads/test_v4.1.pdf
#   size:       控制icon大小
#   hint:       提示信息
#   callback:   回调函数。采用pluginName.MethodName的形式。MethodName请通过阅读源码查找。如果您不懂代码，但还是想添加按钮，有个碰运气技巧：在【右键菜单->常用插件->自定义插件下的插件】基本都是 callback，其余插件基本都是 call
buttons = [
    { disable = false, coordinate = [0, 0], hint = "直达底部", size = "28px", icon = "fa fa-angle-down", callback = "go_top.goBottom" },
    { disable = false, coordinate = [1, 0], hint = "直达顶部", size = "28px", icon = "fa fa-angle-up", callback = "go_top.goTop" },
    { disable = false, coordinate = [2, 0], hint = "夜间模式", size = "18px", icon = "fa fa-adjust", callback = "darkMode.callback" },
    { disable = false, coordinate = [3, 0], hint = "混排优化", size = "17px", icon = "fa fa-align-justify", callback = "md_padding.call" },
    { disable = false, coordinate = [0, 1], hint = "思维导图", size = "22px", icon = "fa fa-code-fork", callback = "markmap.onButtonClick" },
    { disable = false, coordinate = [1, 1], hint = "图片管理", size = "17px", icon = "fa fa-image", callback = "imageReviewer.callback" },
    { disable = false, coordinate = [2, 1], hint = "书签管理", size = "17px", icon = "fa fa-bookmark", callback = "scrollBookmarker.callback" },
    { disable = false, coordinate = [3, 1], hint = "高亮搜索", size = "17px", icon = "fa fa-search", callback = "search_multi.call" },
]
```

![Snipaste_2023-12-17_20-18-12](https://github.com/obgnail/typora_plugin/assets/48992887/b41f4718-f6d8-4164-bbc2-25f72a9b3b49)

然而，quickButton 这个插件有个最大的问题：**需要您对 javascript 有了解**
