### ISSUE TITLE
typora写markdown时候老是自动换行，怎么不换行输出?

### ISSUE THREAD

**Issue by ljacksonl** [obgnail/typora_plugin#355]
问下各位大佬，你们都是如何解决这个问题。导致导出的时候都有换行，样式特别丑。
![image](https://github.com/obgnail/typora_plugin/assets/32628669/762247d6-62b1-4741-86d9-ffbf3b9dbe07)
源代码自动换行，但是typora样式中没有

**Comment by obgnail** [comment]
@ljacksonl 

你是指 soft break 吗？shift+enter 就行

![Snipaste_2023-12-18_23-03-39](https://github.com/obgnail/typora_plugin/assets/48992887/9dbc836d-6e09-4f5b-8cd9-4dd01d9005d0)

**Comment by obgnail** [comment]
@ljacksonl 

你好，请问问题解决了吗？

**Comment by ljacksonl** [comment]
@obgnail  
不好意思，这两天工作有点忙。

非常感谢，功能已经解决。
另外，插件中的文字风格化也特别好用，正好缺一个文字颜色填充板的功能。

**Comment by obgnail** [comment]
@ljacksonl 你好，感谢反馈，已经实现。

目前代码在 dev，等待发版，功能放到 【中英文混排优化】 中，添加如下配置
```toml
[md_padding]
# 最多连续两个换行符，多余的删除
# 举例：\n\n\n\n【a】\n\n\n\n\n【b】 -> \n\n【a】\n\n【b】
REMOVE_MULTI_LINE_BREAK = false
```
