### ISSUE TITLE
章节折叠插件-功能优化

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#361]
> 大佬我又来了 ~_~

章节折叠功能个人认为是一个非常常用的功能，目前的章节折叠菜单太深了，不方便操作。
能否参考左侧文件目录格式实现一个倒三角的快捷操作方式。
![image](https://github.com/obgnail/typora_plugin/assets/26114336/4dde3a41-75a0-41fa-9486-ff732f106c19)

**Comment by SnowMaples** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/26114336/6044d834-378b-45d2-9990-2225a15d7f61)
看到了 有快捷键 。

**Comment by obgnail** [comment]
@SnowMaples 

实际上，可以通过修改配置文件，设置不同的修饰键
```toml
[collapse_paragraph]
# 各个功能对应的修饰键
# 1.支持ctrl/alt/shift的随意组合（如"shift+alt"，"ctrl+shift"）
# 2.但是不能为"alt"（因为alt+click已经被【scrollBookmarker】插件占用），也不能为"shift"（因为shift+click被系统自带的【框选】功能占用）
# 3.若为""，表示不启用此功能
# 4.例如【COLLAPSE_SIBLINGS = "ctrl+alt"】：当用户同时按住键盘ctrl和alt，并且鼠标click标题时，折叠/展开父章节下所有同级的章节
[collapse_paragraph.MODIFIER_KEY]
# 折叠/展开 单个章节
COLLAPSE_SINGLE = "ctrl"
# 折叠/展开 父章节下所有同级的章节
COLLAPSE_SIBLINGS = "ctrl+alt"
# 折叠/展开 当前文件所有同级的章节
COLLAPSE_ALL_SIBLINGS = "ctrl+shift+alt"
# 递归折叠/展开 当前章节
COLLAPSE_RECURSIVE = ""
```

**Comment by obgnail** [comment]
@SnowMaples 

还有一个严格模式，你可以随意点击正文内容，会自动收缩
```toml
[collapse_paragraph]
# 严格模式：只当点击到h1~h6时，才触发折叠/展开。若为false，则自动向上寻找最近的h1~h6
# 非严格模式可能会出现意想不到的事：ctrl+click在typora是非常常用的，当你不小心点错位置，标题就被折叠起来了
STRICT_MODE = true

```
