### ISSUE TITLE
能否在markmap中增加对属性zoom、pan的支持? 

### ISSUE THREAD

**Issue by luoduyu** [obgnail/typora_plugin#443]
经测试，在插入markmap块以后，属性zoom、pan属性不生效。
如果能再增加这colorFreezeLevel、color属性的支持就更好了！感谢！

测试环境：
win10
typora_plugin-1.7.37.zip
typora 1.7.6
![2](https://github.com/obgnail/typora_plugin/assets/3890812/8c17dd71-bacb-4b2d-bf18-1ce025aed4f1)
![1](https://github.com/obgnail/typora_plugin/assets/3890812/203edeb0-7b55-40b8-bc8d-71bc0b7b4bfc)

**Comment by obgnail** [comment]
@luoduyu 你好，感谢反馈。

1. 新版本已经支持 zoom、pan 等 front matter。
2. 同时还添加了 DEFAULT_TOC_OPTIONS、DEFAULT_FENCE_OPTIONS 两个配置，用于配置默认的 options（在没有 front matter 的时候将自动使用默认值）。有需要可以前往配置文件修改：
   ```toml
   [markmap]
   # 默认的toc markmap options
   DEFAULT_TOC_OPTIONS = { duration = 500, initialExpandLevel = -1, zoom = true, pan = true }
   
   # 默认的fence markmap options
   DEFAULT_FENCE_OPTIONS = { duration = 500, initialExpandLevel = -1, zoom = false, pan = false }
   ```

3. 暂不支持 colorFreezeLevel、color 属性。
   1. 使用 color 属性需要引入 d3 库，它好大……
   2. 出于未知原因，colorFreezeLevel 无法正常工作，查看 options 也没有找到 colorFreezeLevel 选项（如下图），我后续再看一下是什么情况

![Snipaste_2024-01-27_20-45-41](https://github.com/obgnail/typora_plugin/assets/48992887/c3bc8d23-6acb-473d-8a5c-c2796ee6492d)
