### ISSUE TITLE
标签怎么关掉啊？

### ISSUE THREAD

**Issue by Tree-New-Beee** [obgnail/typora_plugin#482]
窗口标题下的标签怎么关掉，不想显示出来

**Comment by obgnail** [comment]
@Tree-New-Beee 

你好。

打开文件 `.\plugin\global\settings\settings.user.toml`，添加下面内容

```toml
[window_tab]
ENABLE = false
```
