### ISSUE TITLE
每次打开typora，会自动给目录与标题自动编号，需要每次手动禁用，可以设置默认禁用吗

### ISSUE THREAD

**Issue by CCT-maker** [obgnail/typora_plugin#487]
![Snipaste_2024-02-24_11-01-10](https://github.com/obgnail/typora_plugin/assets/70930287/1adacc41-9c37-4dcc-8d17-5dd27bc57751)

**Comment by obgnail** [comment]
@CCT-maker 

你好。**插件系统的一切功能都可以关闭**。

打开文件 `.\plugin\global\settings\settings.user.toml`，添加下面内容，哪个功能要关闭，就将 true 改成  false

```toml
[auto_number]
# 是否启用插件（总开关，若为false，则关闭所有编号功能）
ENABLE = true
# 启用侧边栏自动编号
ENABLE_SIDE_BAR = true
# 启用正文自动编号
ENABLE_CONTENT = true
# 启用TOC自动编号
ENABLE_TOC = true
# 启用表格自动编号
ENABLE_TABLE = true
# 启用图片自动编号
ENABLE_IMAGE = true
# 启用代码块自动编号
ENABLE_FENCE = true
# 导出时运用样式
ENABLE_WHEN_EXPORT = true
```

**Comment by CCT-maker** [comment]
谢谢哥哥
&nbsp;


陈万业
***@***.***

广西科技大学


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月24日(星期六) 中午11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [obgnail/typora_plugin] 每次打开typora，会自动给目录与标题自动编号，需要每次手动禁用，可以设置默认禁用吗 (Issue #487)





 
@CCT-maker
 
你好。插件系统的一切功能都可以关闭。
 
打开文件 .\plugin\global\settings\settings.user.toml，添加下面内容，哪个功能要关闭，就将 true 改成  false
 [auto_number] # 是否启用插件（总开关，若为false，则关闭所有编号功能） ENABLE = true # 启用侧边栏自动编号 ENABLE_SIDE_BAR = true # 启用正文自动编号 ENABLE_CONTENT = true # 启用TOC自动编号 ENABLE_TOC = true # 启用表格自动编号 ENABLE_TABLE = true # 启用图片自动编号 ENABLE_IMAGE = true # 启用代码块自动编号 ENABLE_FENCE = true # 导出时运用样式 ENABLE_WHEN_EXPORT = true

**Comment by obgnail** [comment]
@CCT-maker 

有兴趣的话，可以阅读一下 `.\plugin\global\settings\请读我.md`，里面介绍了修改配置的方法。

目前插件系统已有 400+ 项配置选项，开发者鼓励您修改配置，以符合自身需求。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by CCT-maker** [comment]
想打开typora的时候，自动跳转到上次最后关闭的文档所看到的行。typora默认打开最后关闭文档并显示文档开头，并不记录上次看的位置。
插件支持记录上次打开文档光标所在行号位置，或者说上次最后阅览文档的位置吗
&nbsp;


陈万业
***@***.***

广西科技大学


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月24日(星期六) 中午11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [obgnail/typora_plugin] 每次打开typora，会自动给目录与标题自动编号，需要每次手动禁用，可以设置默认禁用吗 (Issue #487)





 
@CCT-maker
 
有兴趣的话，可以阅读一下 .\plugin\global\settings\请读我.md，里面介绍了修改配置的方法。
 
目前插件系统已有 400+ 项配置选项，开发者鼓励您修改配置，以符合自身需求。
 
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
@CCT-maker 

插件支持两种记录形式：
1. 在 Typora 运行期间，记录所有的标签页的【最后阅览位置】（一旦退出 Typora，将丢失；一旦关闭某个标签，将丢失该标签的记录）
2. 在重新打开 Typora 时，**记录上次退出时尚未关闭的标签页的【最后阅览位置】**（就是说：上一次 Typora 在还有标签页的时候，你直接右上角退出了）

---

第一个功能默认打开。第二个功能默认关闭，如果需要，可以打开文件 `.\plugin\global\settings\custom_plugin.user.toml`，添加下面内容。

```toml
[reopenClosedFiles]
[reopenClosedFiles.config]
# 打开Typora（打开可丢弃的无标题的标签时）自动恢复上次退出时尚未关闭的标签页
# 注意：只当双击typora.exe打开Typora时生效（因为打开特定文件时，自动恢复上次退出时尚未关闭的标签页，明显不符合用户预期）
auto_reopen_when_init = true
```

> 注意：
> 1. 上面回答中，打开的是 settings.user.toml，这次打开的是 custom_plugin.user.toml。
> 2. 第二个功能在新版本中有 [BUG](https://github.com/obgnail/typora_plugin/issues/455)，我还没来得及修复
