### ISSUE TITLE
每次升级，在代理设置中都会显示一个ip

### ISSUE THREAD

**Issue by 596142041** [obgnail/typora_plugin#488]
这IP地址可以使用配置文件配置么？否则每次都需要手动删除，否则就容易升级失败。
![image](https://github.com/obgnail/typora_plugin/assets/4958182/2fcbe890-4949-4b3a-9be4-6036c3c5b868)

**Comment by obgnail** [comment]
@596142041 

你好。

打开文件 `.plugin\global\settings\custom_plugin.user.toml`，添加下面内容

```toml
[pluginUpdater]
[pluginUpdater.config]
# 众所周知，有些地区无法裸连github，需要使用代理（如：http://127.0.0.1:7890）
# 若值为空，则将弹出窗口，让用户填入代理；若有值，则将直接使用此代理，不再弹出窗口
# 除非你固定使用某代理，否则不建议使用此配置
proxy = ""
```

> 注意：如果您设置了 proxy 配置选项，将不再弹出弹窗，默认使用您的 proxy，所以只在您固定使用某个 proxy 时推荐修改此配置。
