### ISSUE TITLE
混排优化、代码栏优化

### ISSUE THREAD

**Issue by lxb9764** [obgnail/typora_plugin#491]
1、混排优化
有一点点BUG，遇到代码框之后的中英文混排不会被调整

2、代码栏优化
能不能去掉代码栏下面的Fence x-x这样字体呢？

**Comment by obgnail** [comment]
@lxb9764 

你好，感谢反馈。

## 混排优化

1.  **支持调整代码块，不过只会调整注释里的文字**。
2. 同时，这也是合理的，比如 `let s = "abc汉字def"` 这句代码，是不能会去调整字符串内容的。
3. 目前支持优化的语言：cpp, c, java, javascript, typescript, csharp, go, sql, bash, python, ruby。


## 代码栏优化

**插件的一切功能都是可以关闭的**。

打开文件 .\plugin\global\settings\settings.user.toml，添加下面内容，哪个功能要关闭，就将 true 改成 false（针对你的情况，设置 ENABLE_FENCE = false 即可）

```toml
[auto_number]
# 是否启用插件（总开关，若为false，则关闭所有编号功能）
ENABLE = true
# 启用侧边栏自动编号
ENABLE_SIDE_BAR = true
# 启用正文自动编号
ENABLE_CONTENT = true
# 启用TOC自动编号
ENABLE_TOC = true
# 启用表格自动编号
ENABLE_TABLE = true
# 启用图片自动编号
ENABLE_IMAGE = true
# 启用代码块自动编号
ENABLE_FENCE = true
# 导出时运用样式
ENABLE_WHEN_EXPORT = true
```
