### ISSUE TITLE
如何参与插件开发

### ISSUE THREAD

**Issue by pyz610173878** [obgnail/typora_plugin#493]
您好，我在使用typora有一个痛点想着自己独立解决一下（开发一个插件），能否根据现有项目进行扩展，到时候提交PR。

**Comment by obgnail** [comment]
@pyz610173878 

你好，完全没有问题的。

你可以看一下 [开发文档](https://github.com/obgnail/typora_plugin/blob/master/plugin/custom/%E8%AF%B7%E8%AF%BB%E6%88%91.md)

**Comment by pyz610173878** [comment]
你好，开发文档中`custom_plugin.user.toml`文件的路径需要修改一下，少了/global/settings/custom_plugin.user.toml。刚刚找半天没找到，用的everything全局搜索到的😂。
![Uploading image.png…]()

**Comment by pyz610173878** [comment]
> 开发过程有什么问题可以在下面留言，我尽量回复

谢谢大佬😁

**Comment by obgnail** [comment]
@pyz610173878 

你可以根据下面的步骤，先把插件跑起来。

---

## 示例：快速开始

步骤一：在 `./plugin/custom/custom_plugin.user.toml` 添加如下配置：

```toml
[helloWorld]
name = "你好世界"  # 右键菜单中展示的名称
enable = true     # 是否启用此自定义插件
hide = false      # 是否在右键菜单中隐藏
order = 1         # 在右键菜单中的出现顺序（越大越排到后面，允许负数）

	[helloWorld.config]
	hotkey = "ctrl+alt+u"
	console_message = "i am in process"
	show_message = "this is hello world plugin"
```



步骤二：创建文件 `./plugin/custom/plugins/helloWorld.js` 文件，将下面代码保存到该文件中：

```javascript
// ./plugin/custom/plugins/helloWorld.js

class helloWorld extends BaseCustomPlugin {
    hint = () => "this is hello world hint"
    
    hotkey = () => [this.config.hotkey]
    
    process = () => {
        console.log(this.config.console_message);
        console.log("[helloWorldPlugin]：", this);
    }

    callback = anchorNode => {
        alert(this.config.show_message);
    }
}

module.exports = { plugin: helloWorld };
```



验证：完成以上步骤后，重启 Typora。

1. 打开 devtool，发现控制台输出了 `i am in process` 和 插件对象。你可以仔细看看 this 拥有的属性和方法。
2. 鼠标右键，弹出菜单，鼠标悬停在 `常用插件 -> 自定义插件 -> 你好世界`。发现出现了 hint，显示 `this is hello world hint`。
3. 鼠标右键，弹出菜单，点击 `常用插件 -> 自定义插件 -> 你好世界`。发现弹出了提示框，显示 `this is hello world plugin`。
4. 键入快捷键 `ctrl+alt+u`，发现同样弹出了提示框。

**Comment by pyz610173878** [comment]
我已经跑起来了，在看这个实战示例1。

**Comment by pyz610173878** [comment]
想问下，有什么办法修改了配置，不需要重启`Typora`也可以生效。

**Comment by pyz610173878** [comment]
> 上面的 helloWrold 示例，说明了 hint、hotkey 、process 、callback 四个最常用的方法，有兴趣可以看看。

谢谢佬，我今天争取提交一次PR。

**Comment by obgnail** [comment]
> 想问下，有什么办法修改了配置，不需要重启 `Typora` 也可以生效。

1. 暂时没有。
2. 和大多数项目一样，toml 配置文件只负责初始化。接着将其全部封装到 this.config 属性中，后续由 this.config 接管。
3. 在插件后续运行中，如果你希望修改配置，直接操作 this.config 就可以了。
4. 如果你觉得每次修改都要重启 Typora 比较麻烦，可以打开 `settings.user.toml` 文件，添加下面内容。然后，在你需要重启 Typora 的时候，就可以键入 ctrl+shift+n 启动一个新的实例，并且会在重启后自动打开 devtool。

```toml
[test]
ENABLE = true
```
