### ISSUE TITLE
resourceOperation 插件优化建议

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#524]
**有了您开发的这个插件，效率高了不少，感谢您。搞个打赏吧，请你喝咖啡^_^。**

**需求如下**
> 希望resourceOperation可以支持自定义删除文件操作。支持单个文件预览（目前我主要冗余的是图片）、删除、复选框勾选支持批量删除，具体想法如下

![image](https://github.com/obgnail/typora_plugin/assets/26114336/f945d124-2786-4d0f-b0d2-6cbdee359fdf)

再次感谢您的付出！

**Comment by xiaogithubooo** [comment]
追问：这个插件可以对文件批量检查么，检查图片的时候就不用一个一个文件使用了

**Comment by SnowMaples** [comment]
可以的，你可以尝试一下，目前只会列出来，不能直接删除。

**Comment by obgnail** [comment]
@SnowMaples @xiaogithubooo 

你好，感谢反馈。


插件默认就是批量检查的，**会检查 mountFolder （就是左侧侧边栏里的根目录）下的所有文件**，所以一般会花费数秒到数十秒的时间（依照根目录里的文件数量而定）

---

如果你仔细查看 resourceOperation 的配置，其实是支持 **静默删除** 文件的，我并没有写交互逻辑，一方面是因为 delete/move 都是危险操作，我也不能保证插件没有 BUG，我不太敢删除；另一方面是因为私以为资源管理是个很低频的操作，写交互页面太麻烦（是我太懒了

```toml
[resourceOperation]
[resourceOperation.config]
# 分析后的操作(delete和move都是危险操作，请务必查看report之后才选用)
#   1.report: 生成报告
#   2.delete: 直接删除
#   3.move  : 移动到当前文件夹
operation = "report"
```

---

我这段时间不太有空，可能只有周末有时间处理，如果二位有心的话，可以提一个 PR（球球了

```js
```
