### ISSUE TITLE
启停插件问题

### ISSUE THREAD

**Issue by zhouxinghong** [obgnail/typora_plugin#532]
您好！感谢您这个很酷的插件。
需求1：
当我第一次选择使用2个插件，而其他插件都停止了。
当我再一次点击启停插件时候，所有的插件又被全部选中了，这不是用户想要的。正确的是应该选中用户上次选中的插件。

需要2：
无法单独使用其中某一个插件。例如：图像预览插件

建议：
建议将启停插件改为插件管理更为合理。

Windows
最新版插件
1.8.9

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by zhouxinghong** [comment]
非常感谢您及时修复！👍👏🎉

**Comment by zhouxinghong** [comment]
设置后样式变为这样了。
![2024-03-27_插件样式乱了](https://github.com/obgnail/typora_plugin/assets/54253524/3e33d11f-0735-421d-9d49-34869d652b58)

**Comment by obgnail** [comment]
@zhouxinghong 

每个按钮都对应一个插件，你把插件关了，那么按钮就消失了。

---

如果你想自定义按钮的排布和功能，可以修改配置文件 `.\plugin\global\settings\custom_plugin.user.toml`，添加下面内容：

我给你加了各个参数的解释，你看着修改就行。

```toml
[quickButton]
[quickButton.config]
# 添加的按钮：
#   disable:      禁用此按钮
#   coordinate:   按钮坐标。往上为x轴正方向，往左为y轴正方向，从零开始计数
#   icon:         按钮图标。填入css class。支持font-awesome-4.1.0和ionicons-2.0.1，所有的图标及其对应的css class请参考：https://www.adfwebmagazine.jp/wp-content/uploads/test_v4.1.pdf  和  https://ionic.io/ionicons/v2
#   size(可选):    图标大小。默认17px
#   color(可选):   图标颜色。默认跟随当前主题的配色方案
#   bgColor(可选): 图标背景色。默认跟随当前主题的配色方案
#   hint:         提示信息
#   callback:     回调函数。采用pluginName.MethodName的形式（功能就像hotkey.default.toml中的plugin参数和function参数的合体）
#                     MethodName请通过阅读源码查找。如果您不懂代码，但还是想添加按钮，有个碰运气技巧：在【右键菜单->常用插件->自定义插件下的插件】基本都是XXX.callback，其余插件基本都是XXX.call
#   evil(危险):    自定义回调函数。功能同hotkey.default.toml中的evil参数（它能用的，这里也能用）。这里的文本内容会被eval()。如果设置此参数，callback参数会失效
buttons = [
    { disable = false, coordinate = [0, 0], hint = "直达底部", size = "28px", icon = "fa fa-angle-down", callback = "go_top.goBottom" },
    { disable = false, coordinate = [1, 0], hint = "直达顶部", size = "28px", icon = "fa fa-angle-up", callback = "go_top.goTop" },
    { disable = false, coordinate = [2, 0], hint = "文字风格", size = "17px", icon = "fa fa-font", callback = "text_stylize.call" },
    { disable = false, coordinate = [3, 0], hint = "混排优化", size = "17px", icon = "fa fa-align-justify", callback = "md_padding.call" },
    { disable = false, coordinate = [0, 1], hint = "思维导图", size = "22px", icon = "fa fa-code-fork", callback = "markmap.onButtonClick" },
    { disable = false, coordinate = [1, 1], hint = "图片管理", size = "17px", icon = "fa fa-image", callback = "imageReviewer.callback" },
    { disable = false, coordinate = [2, 1], hint = "书签管理", size = "17px", icon = "fa fa-bookmark", callback = "scrollBookmarker.callback" },
    { disable = false, coordinate = [3, 1], hint = "高亮搜索", size = "17px", icon = "fa fa-search", callback = "search_multi.call" },
]
```
