### ISSUE TITLE
您好！使用的感受

### ISSUE THREAD

**Issue by zhouxinghong** [obgnail/typora_plugin#539]
您好！使用感受如下：
1、只读模式建议允许复制内容；
2、只读模式建议增加一个快捷按钮，不然每一次需要右键菜单，非常的麻烦。
3、请特别重视扩展运行性能与可靠性，并不断提高扩展运行性能及可靠性，否则添加再多的功能也无济于事；

希望您可以听取并改进它，🎉👍😜

**Comment by obgnail** [comment]
@zhouxinghong 

你好，感谢反馈。

1. 只读模式允许复制内容。框选文字，然后 ctrl+C 就行了

2. 只读模式的默认快捷键：ctrl+shift+r。

   如需更改快捷键，请打开配置文件 `\plugin\global\settings\settings.user.toml`，添加如下内容

   ```toml
   [read_only]
   # 进入和脱离只读模式的快捷键
   HOTKEY = "ctrl+shift+r"
   ```

3. 此项目非常注重性能，如果有兴趣，可以看一下 [历史版本](https://github.com/obgnail/typora_plugin/releases) 的 changelog，里面有很多性能优化

**Comment by obgnail** [comment]
@zhouxinghong 

所有的快捷按钮都是可以自定义的。

如需更改快捷按钮，请打开配置文件 \plugin\global\settings\custom_plugin.user.toml，添加如下内容

```toml
[quickButton]
[quickButton.config]
# 添加的按钮：
#   disable:      禁用此按钮
#   coordinate:   按钮坐标。往上为x轴正方向，往左为y轴正方向，从零开始计数
#   icon:         按钮图标。填入css class。支持font-awesome-4.1.0和ionicons-2.0.1，所有的图标及其对应的css class请参考：https://www.adfwebmagazine.jp/wp-content/uploads/test_v4.1.pdf  和  https://ionic.io/ionicons/v2
#   size(可选):    图标大小。默认17px
#   color(可选):   图标颜色。默认跟随当前主题的配色方案
#   bgColor(可选): 图标背景色。默认跟随当前主题的配色方案
#   hint:         提示信息
#   callback:     回调函数。采用pluginName.MethodName的形式（功能就像hotkey.default.toml中的plugin参数和function参数的合体）
#                     MethodName请通过阅读源码查找。如果您不懂代码，但还是想添加按钮，有个碰运气技巧：在【右键菜单->常用插件->自定义插件下的插件】基本都是XXX.callback，其余插件基本都是XXX.call
#   evil(危险):    自定义回调函数。功能同hotkey.default.toml中的evil参数（它能用的，这里也能用）。这里的文本内容会被eval()。如果设置此参数，callback参数会失效
buttons = [
     # 默认的按钮
    { disable = false, coordinate = [0, 0], hint = "直达底部", size = "28px", icon = "fa fa-angle-down", callback = "go_top.goBottom" },
    { disable = false, coordinate = [1, 0], hint = "直达顶部", size = "28px", icon = "fa fa-angle-up", callback = "go_top.goTop" },
    { disable = false, coordinate = [2, 0], hint = "文字风格", size = "17px", icon = "fa fa-font", callback = "text_stylize.call" },
    { disable = false, coordinate = [3, 0], hint = "混排优化", size = "17px", icon = "fa fa-align-justify", callback = "md_padding.call" },
    { disable = false, coordinate = [0, 1], hint = "思维导图", size = "22px", icon = "fa fa-code-fork", callback = "markmap.onButtonClick" },
    { disable = false, coordinate = [1, 1], hint = "图片管理", size = "17px", icon = "fa fa-image", callback = "imageReviewer.callback" },
    { disable = false, coordinate = [2, 1], hint = "书签管理", size = "17px", icon = "fa fa-bookmark", callback = "scrollBookmarker.callback" },
    { disable = false, coordinate = [3, 1], hint = "高亮搜索", size = "17px", icon = "fa fa-search", callback = "search_multi.call" },
    
    # 用户自己的按钮
    { disable = false, coordinate = [4, 0], hint = "只读模式", size = "20px", icon = "fa fa-book", color = "#f0f8ff", bgColor = "#22B130", callback = "read_only.call" },
]
```
