### ISSUE TITLE
【小优化】只读模式拷贝不了照片

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#559]
#539 中提到只读模式下支持对文本的复制，那能不能顺带支持对图片的复制😯？

**Comment by obgnail** [comment]
@xiaogithubooo 

已实现，代码中 [dev](https://github.com/obgnail/typora_plugin/commit/e0dfae71b43bea9f2d761c42cdcfa98719ec9164)，等待发版。

新增了一个配置选项，如此你就可以在右键菜单中复制图片了。
```toml
[read_only]
# 只读状态下禁用右键菜单的时候，哪些菜单选项保持可用（可选值需要您开打调试工具，查找其中 data-key）
REMAIN_AVAILABLE_MENU_KEY = ["typora-plugin", "dev-tool", "copy-img"]
```
