### ISSUE TITLE
功能请求：PDF批量导出

### ISSUE THREAD

**Issue by Anyayay** [obgnail/typora_plugin#560]
对 当前目录/打开的标签页的文件 批量导出pdf

**Comment by obgnail** [comment]
@Anyayay 

你好，感谢反馈。

批量导出功能不好搞。

1. Typora 并没有批量导出功能，因为不能 hook 这个接口。
2. 导出功能和当前 DOM 树高度绑定。

结论：
如果真的要实现此功能，目前我想到的方法只能是：将原来手动导出的流程自动化。即：切换到目标文件，然后导出

**Comment by zhouxinghong** [comment]
目前没有任何一款工具做批量导pdf的功能。。。应该是认为意义不大。

**Comment by Zxis233** [comment]
不知道有没有办法将 导出为PDF 绑定快捷键呢
查询了官方文档，windows下只有传统窗口界面可以绑定快捷键，一体化下不行。
不知道能否用`Hotkey`插件进行手动设置

**Comment by obgnail** [comment]
@Zxis233 

打开文件 .\plugin\global\settings\hotkey.user.toml，加入以下内容，之后使用 ctrl+alt+e 导出

```toml
[fastExport]
desc = "快读导出"
enable = true
hotkey = "ctrl+alt+e"
evil = '() => ClientCommand.export({"type": "pdf", "appendBody": "", "runCommand": false, "runCommandStr": "", "showOutput": false, "key": "pdf"});'
```
