### ISSUE TITLE
文件模板

### ISSUE THREAD

**Issue by xutiansama** [obgnail/typora_plugin#561]
如何自定义文件模板,有教程吗

**Comment by obgnail** [comment]
@xutiansama 

你好，目前绝大多数插件的配置都是通过修改配置文件完成的。

打开文件 `.\plugin\global\settings\custom_plugin.user.toml`，添加下面内容：

```toml
[templater]
[templater.config]
# 模板
# 当前支持的模板变量：
#   {{date}}：当前日期
#   {{time}}：当前时间
#   {{weekday}}：当前周几
#   {{datetime}}：当前日期时间
#   {{yesterday}}：昨天日期
#   {{tomorrow}}：明天日期
#   {{random}}：随机数
#   {{title}}：新建文件的标题
#   {{folder}}：当前文件的目录
#   {{filepath}}：新建文件的路径
#   {{range}}：当前选取的文字
#   {{uuid}}：uuid
[[templater.config.template]]
name = "标准模板"
text = """---
title: {{title}}
date: {{date}}
tags:
---

"""
[[templater.config.template]]
name = "日记"
text = """---
title: {{title}}
date: {{date}} {{weekday}}
---

"""
```
