### ISSUE TITLE
安装后大纲的数字序号没办法改为默认的格式

### ISSUE THREAD

**Issue by jellzone** [obgnail/typora_plugin#578]
安装后大纲的序号都是 0.0.1 0.0.2 这样的格式了，没办法接受，只能卸载了

**Comment by obgnail** [comment]
@jellzone 

你好，感谢反馈。**插件的任何功能都支持单独关闭**。


## 方法一：修改配置文件，定点爆破不需要的功能

打开配置文件 ./plugin/global/settings/settings.user.toml，填入下面内容。不需要开启的功能置为 false 即可。

```toml
[auto_number]
# 启用侧边栏自动编号
ENABLE_SIDE_BAR = true
# 启用正文自动编号
ENABLE_CONTENT = true
# 启用TOC自动编号
ENABLE_TOC = true
# 启用表格自动编号
ENABLE_TABLE = true
# 启用图片自动编号
ENABLE_IMAGE = true
# 启用代码块自动编号
ENABLE_FENCE = true
# 导出时运用样式
ENABLE_WHEN_EXPORT = true
```

> 如何修改配置文件请参考[这里](https://github.com/obgnail/typora_plugin/tree/1.8.32?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)

## 方法二：单独关闭插件

任何不喜欢的插件，都可以永久关闭。

操作方法：右键菜单 -> 非常用插件 -> 启停插件。

对于你的情况，请关闭【自动编号】插件。
