### ISSUE TITLE
现在似乎没有办法通过右键菜单卸载插件了，在配置文件里也没有找到对应的配置

### ISSUE THREAD

**Issue by wenxi-zhao** [obgnail/typora_plugin#581]
现在似乎没有办法按照 Read.me 里面的方法，通过右键菜单卸载插件。另外，在配置文件里面也没有找到对应的卸载插件的方法。
现在应该如何卸载呢？

**Comment by obgnail** [comment]
@wenxi-zhao 

你好，感谢反馈。

我刚刚试了一下，没有问题呀。

你试试 【右键菜单 -> 不常用插件 -> 启停插件】应该可以弹出如下弹窗，取消勾选即可。

你是遇到什么问题吗？麻烦描述一下。

![img_2024-05-07_16-46-55](https://github.com/obgnail/typora_plugin/assets/48992887/ef7656f5-2eee-4e59-a26b-677f2070e3da)

**Comment by obgnail** [comment]
如果你是希望手动修改配置文件来禁用某些插件，可以修改 ENABLE/enable 字段。其中：
- 一级插件的字段是 ENABLE
- 二级插件的字段是 enable

---
比如：

如果你想要禁用一级插件【标签页管理】，就可以在 settings.user.toml 文件里加入如下内容：

```toml
[window_tab]
# 是否启用插件
ENABLE = false
```

如果你想禁用二级插件【kanban】，就可以在 custom_plugin.user.toml 文件里加入如下内容：
```toml
[kanban]
# 是否启用此二级插件
enable = false
```

修改配置文件前，请务必阅读 [请读我](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md)
