### ISSUE TITLE
用了插件之后图片、表格自动添加名称

### ISSUE THREAD

**Issue by 87zrjojo** [obgnail/typora_plugin#610]
我想修改自动添加的名称，请问怎么操作呢？比如Table 1-1，我想表格都以XX表 1-1，1-2……这样编排，在哪里定义呢？

**Comment by obgnail** [comment]
@87zrjojo 

你好，感谢反馈。

打开配置文件 `plugin/global/settings/settings.user.toml`，添加如下内容：
```toml
[auto_number]
# 是否启用插件
ENABLE = true
# 启用侧边栏自动编号
ENABLE_SIDE_BAR = true
# 启用正文自动编号
ENABLE_CONTENT = true
# 启用TOC自动编号
ENABLE_TOC = true
# 启用表格自动编号
ENABLE_TABLE = true
# 启用图片自动编号
ENABLE_IMAGE = true
# 启用代码块自动编号
ENABLE_FENCE = true
# 编号的下标名称
NAMES = { table = "表格", image = "图片", fence = "代码块" }
```

具体到你的情况，应该修改 ENABLE_IMAGE  和 NAMES 

> 修改配置文件的方法，请参考 [这里](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md)
