### ISSUE TITLE
请问是否可以针对不同代码语言做行号和折叠？

### ISSUE THREAD

**Issue by lllanaaa** [obgnail/typora_plugin#617]
比如xml和json非常需要可以折叠起来，方便看

**Comment by obgnail** [comment]
记录：typora 使用 codeMirror 作为代码块，似乎每个语言的折叠都需要引入一个 js 文件。

[参考用法](https://codemirror.net/3/demo/folding.html)

**Comment by obgnail** [comment]
@lllanaaa 

你好，感谢反馈。需求已实现。麻烦升级到新版本试用。

![IMG_2024-09-25_18-13-45 (1)](https://github.com/user-attachments/assets/2408dbe5-853e-4fa4-9402-884a88fba500)

注意，此功能默认关闭，需要手动开启：修改 settings.user.toml 文件，新增如下内容：

```toml
[fence_enhance]
# 针对不同代码语言做行号和折叠
ENABLE_LANGUAGE_FOLD = true
```
