### ISSUE TITLE
建议：【升级插件】功能

### ISSUE THREAD

**Issue by DoubleW2w** [obgnail/typora_plugin#635]
【升级插件】功能可以改为「自动检查更新」类似的功能。

参考的是 当typora 存在版本时，打开 typora 会自动弹出弹窗
内容是 **版本号的变动**以及 **版本变动的内容**。它好像还分了是否要更新至「开发版」。

本来想找这个自动检查更新的功能，代码是怎么实现的0.0，没找到。可能被封在某个 dll 文件中？。

os：知道你更新的频繁， 所以我常常右键-> 升级插件 用的挺多。确实存在升级，有时候想看升级了什么。

**Comment by DoubleW2w** [comment]
还有一个问题是，当在 typora 升级插件时，你是用的命令行环境这个功能去操作的吧。

它升级完，tancha弹窗还没法关（好像置于typora页面的顶层了）。 我的关闭方式是 要么重开 typora，要么就选择 「摸黑」找到命令行环境，然后选择隐藏。

![image](https://github.com/obgnail/typora_plugin/assets/73921620/89ef1000-93d9-4a5f-a956-c3eeeb7d9c44)

**Comment by obgnail** [comment]
@DoubleW2w 

你好，感谢反馈。

1. 一键升级功能很老了，很久没有更新了。
2. 目前系统默认会在 Typora 打开的 5 分钟后执行一次静默升级操作，成功与否都不弹窗。你也可以改成轮询检测，具体可以看看插件 `pluginUpdater` 的配置选项（如下）。如何修改配置请阅读 [readme](https://github.com/obgnail/typora_plugin?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)。
3. 这么设计的原因是：本项目是敏捷迭代的，两天一个版本，弹窗提示太频繁了。
4. 升级操作是 `./plugin/updater/updater.exe` 完成的，其源码是同目录下的 `updater.go`。其实我一直想将升级逻辑从 golang 迁移到 NodeJS，我之前还提了个 [问卷](https://github.com/obgnail/typora_plugin/issues/548)，一直没有实现，太懒了。~~等待好心人给我提PR~~
5. 还有一种关闭弹窗的方式：光标定位到弹窗的输入框，然后键入 esc。


```toml
############### pluginUpdater ###############
[pluginUpdater]
# 右键菜单中展示的名称
name = "升级插件"
# 是否启用此二级插件
# 注意：此插件目前仅支持windows系统，若为其他系统，则此插件失效
# 注意：此插件依赖于commander插件，若禁用了commander，则此插件失效
# 注意：若您删除了文件./plugin/updater/updater.exe，则此插件失效
enable = true
# 是否在右键菜单中隐藏
hide = false
# 在右键菜单中的出现顺序（越大越排到后面，允许负数）
order = 1
# 插件配置
[pluginUpdater.config]
# 快捷键
hotkey = ""
# 众所周知，有些地区无法裸连github，需要使用代理（如：http://127.0.0.1:7890）
# 若值为空，则将弹出窗口，让用户填入代理；若值不为空，则将直接使用此代理，不再弹出窗口
# 除非你固定使用某代理，否则不建议使用此配置
proxy = ""
# 手动升级时是否弹窗
#   - always : 总是弹出（等待程序执行完毕后一次性弹出）
#   - error  : 只在异常时弹出
#   - silent : 总是静默
#   - echo   : 立即回显
exec_show = "echo"
# 是否启用自动静默升级（若为false，则以下配置全部失效）
# 自动升级有两个策略：
#   - 策略一：打开Typora一段时间后，执行一次升级流程
#   - 策略二：每隔一段时间，执行一次升级流程
auto_update = true
# 策略一（单位：ms，若<0，则不使用此策略）
start_update_interval = 300000   # 1000 * 60 * 5
# 策略二（单位：ms，若<0，则不使用此策略）
update_loop_interval = -1
# 自动升级时使用的回显方式（可选项和exec_show相同）
auto_exec_show = "silent"
```
