### ISSUE TITLE
资源管理插件不应该把.gitignore文件也放入

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#674]
![image](https://github.com/user-attachments/assets/1792cfc7-4bd1-40e9-8ad8-5a08c0e0a2de)

**Comment by xiaogithubooo** [comment]
想了想又觉得合理...

**Comment by obgnail** [comment]
1. 本插件是通过后缀名来判断是否是资源的，看以下配置选项，collect_file_without_suffix 默认为 true，所以默认会把无后缀文件也作为资源。
2. 同时 NodeJS 的 path.extname 会判定 .gitignore 没有 extname。
3. 所以 .gitignore 就会被包含进来。
4. 最佳的方案肯定是判断 file magic number，一方面我不想自己写，一方面我又不想为了此功能引入其他包，于是放着没管。事实是连 Windows 都懒得管这件事，也是直接使用后缀判定的，操作系统都如此，我就跟着摆烂了。

```toml
[resourceOperation]
# 什么后缀判定为资源
resource_suffix = [".jpg", ".jpeg", ".png", ".gif", ".svg", ".webp", ".webm", ".bmp", ".mp3", ".mp4", ".ogg", ".image", ".jfif", ".gif!large"]
# 对于无后缀名的文件是否加入资源列表
collect_file_without_suffix = true
```

```js
a = "D:\\golang\\src\\github.com\\obgnail\\typora_plugin\\.gitignore"
const b = require("path").extname(a)
console.log(b) // 输出空串。node 判定 .gitignore 这类 dot file 没有 extname
```
