### ISSUE TITLE
能添加自动补全功能吗（针对latex）

### ISSUE THREAD

**Issue by ZAerBeiGa** [obgnail/typora_plugin#697]
markdown感觉不需要自动补全，但latex挺需要的
比如\frac{}{}
能输入\，光标下弹出补全窗口，出现基本所有语法
输入\f，补全窗口里是
* \frac
* \forall
* ...
然后回车选择\frac
然后结果是\frac**{}{}**
即自动补充和**加括号**

**Comment by obgnail** [comment]
@ZAerBeiGa 

你好，感谢反馈。

已经实现。麻烦升级到新版本试用一下。

**仅支持 inline_math，不支持 block_math**。

> 原因：公式块使用的是开源的 codeMirror 组件，与我的插件设计冲突，实现不了 —— codeMirror 通过 textarea 保存内容，无法通过 rangy 获取键入的文字

使用：修改 settings.user.toml 文件中 slash_commands 的 COMMANDS 参数，需要自动补全什么自己加

```toml
[slash_commands]
# 命令列表
#  - enable:    是否启用
#  - type:      snippet/command/gen-snp（snippet: 在调用时插入文字片段；command: 在调用时执行逻辑命令；gen-snp: 在调用时执行函数，返回待插入的文字片段，适用于插入动态内容）
#  - scope:     当光标处在哪个位置可用。可选：plain/inline_math（默认为plain）
#  - icon(可选): 使用emoji作为图标
#  - hint(可选): 提示信息
#  - keyword:   关键词，必须唯一
#  - callback:  若type=snippet，则填入需要插入的文字片段；若type=command，则填入回调函数；若type=gen-snp，则填入返回字符串的函数
COMMANDS = [
    ...
    { enable = true, type = "snippet", scope = "inline_math", icon = "🧩", keyword = "beta", callback = "\\beta " },
    { enable = true, type = "snippet", scope = "inline_math", icon = "🧩", keyword = "epsilon", callback = "\\epsilon " },
    { enable = true, type = "snippet", scope = "inline_math", icon = "🧩", keyword = "rightarrow", callback = "\\rightarrow " },
]
```

![IMG_2024-08-08_21-06-01](https://github.com/user-attachments/assets/8e86ac7c-f99f-40b2-b184-54eb5b784e43)
