### ISSUE TITLE
auto_number插件设置enable = false了还是还是会生效

### ISSUE THREAD

**Issue by BloodlineL** [obgnail/typora_plugin#700]

**Comment by obgnail** [comment]
@BloodlineL 

你好。我试了，没有问题的。大概率是你配置错了。实际上所有的插件的加载流程共用一套代码，不太可能某个插件会单独出现问题。

## 方法一

在 `settings.user.toml` 文件写入如下内容
```toml
[auto_number]
ENABLE = false
```

## 方法二

如果只是想单独启停某个插件，可以不通过修改配置文件实现：

右键菜单 -> 少用插件 -> 启停插件 -> 取消勾选【自动编号】。
