### ISSUE TITLE
自动编号问题

### ISSUE THREAD

**Issue by 596142041** [obgnail/typora_plugin#709]
在文件使能自动编号，当前光标移动至编号的行，编号会自动隐藏，如下图：
![微信截图_20240816144544](https://github.com/user-attachments/assets/b4634792-7ab4-4dea-bd36-208f375c06af)
将光标移开该行之后，编号自动显示如下图：
![微信截图_20240816142947](https://github.com/user-attachments/assets/54463a82-28c3-4de5-82bd-cd779cad6bfd)
这是哪儿的问题了，我看了配置文件里面也没有该对应的配置项目，之前的版本是没有这问题。当前使用的插件版本是1.10.14版本。

**Comment by 596142041** [comment]
并且还只会在3级标题及其3级以上标题才会出现

**Comment by obgnail** [comment]
@596142041 

你好，感谢反馈。

和 #585 issue 类似。

原因：【自动编号】插件和你使用 Theme 冲突了，你可以试试切换回 默认的 github theme，问题就消失了。

> 根本原因：本插件系统不是官方的，主题作者在实现的时候不会主动兼容这个项目。

麻烦提供一下你使用的 Theme 名称，我看能不能兼容（虽然我猜大概率无法兼容）（虽然我猜大概率无法兼容）

**Comment by 596142041** [comment]
是，是主题的原因。主题如附件，
[drake-google.css.txt](https://github.com/user-attachments/files/16634038/drake-google.css.txt)

**Comment by obgnail** [comment]
原因：

drake-google.css 存在如下代码，当 h3-h6 聚焦时，将 ::before 伪元素置为不可见。

```css
h3.md-focus:before, h4.md-focus:before, h5.md-focus:before, h6.md-focus:before {
    visibility: hidden;
}
```

那么，我该怎么做呢？覆盖上述逻辑，强制 visibility 为 visible？
