### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by lyidle** [obgnail/typora_plugin#724]
# window_tab的宽度有一点小了，还有callouts有些有高度塌陷问题
## callouts_normal
自己稍微美化了一下
![Clip_2024-08-25_18-33-11](https://github.com/user-attachments/assets/266414c0-b9c9-489c-8cc8-41102630fd9b)
### callouts_revision
![image](https://github.com/user-attachments/assets/98a3123e-a008-415c-9b09-bb414cc6bc40)
## window_tab revision
![Clip_2024-08-25_18-37-16](https://github.com/user-attachments/assets/c17ce927-4e01-4b68-a329-cd3b3e674c0d)
![Clip_2024-08-25_18-37-26](https://github.com/user-attachments/assets/5130fb16-d2ba-486c-8b60-82c968c75812)
### css
``` css
div#outline-content::-webkit-scrollbar-thumb,
.native-window content::-webkit-scrollbar-thumb,
div#plugin-window-tab .tab-bar::-webkit-scrollbar-thumb{
    border-radius: var(--overflow-scorllbar-thumb-border-radius) !important;
    background: var(--overflow-scorllbar-thumb-background) !important;
}

div#outline-content::-webkit-scrollbar,
.native-window content::-webkit-scrollbar,
div#plugin-window-tab .tab-bar::-webkit-scrollbar{
    background-color: #F9F1FF!important;
}

div#plugin-window-tab .tab-bar::-webkit-scrollbar{
    display: none!important;
}
div#plugin-window-tab .tab-bar.active::-webkit-scrollbar{
    display: block!important;
}
```
### JavaScript
``` js
        // #region 改变滚动条
        const windowNavScroll = document.querySelector('div#plugin-window-tab .tab-bar')
        const windowNavWidth = document.querySelector('#write')
        // 创建观察对象
        const myObserver = new ResizeObserver(entries => {
            entries.forEach(entry => {
                // write的宽度 + 12滚动条宽度 + 左右padding
                windowNavScroll.style = `width: ${entry.contentRect.width + 12 + +window.getComputedStyle(windowNavWidth).paddingRight.replace('px', '') + +window.getComputedStyle(windowNavWidth).paddingLeft.replace('px', '')}px!important;`
            })
        })
        myObserver.observe(windowNavWidth)
        windowNavScroll.addEventListener('mouseenter', () => {
            windowNavScroll.classList.add('active')
        })
        windowNavScroll.addEventListener('mouseleave', () => {
            windowNavScroll.classList.remove('active')
        })
        // #endregion 改变滚动条
```

**Comment by obgnail** [comment]
@lyidle 

你好，感谢反馈。

## callouts **有些类型** 有高度塌陷问题

我想你应该也比较奇怪，为什么是有些，而不是全部

原因是：callouts 插件诞生得很早，当时 Typora 还不支持 callouts 功能，然后 Typora 官方在 1.8 版本原生支持了 callouts，原生功能与插件发生重叠。

> 你可以在 Typora 偏好设置的 `Markdown -> Markdown 扩展语法 -> Github 风格警报框` 关闭此功能。

保留此插件的原因：
1.  原生功能仅支持五种类型的 callouts（NOTE，TIP，IMPORTANT，WARNING，CAUTION）
2. 原生功能不支持 fold callouts（如： > [!NOTE]-）。
3. 此插件兼容原生功能（功能上兼容，样式会有点差异）

你会发现，出现高度塌陷问题就是上述的五种类型。

总结：**这是你使用的 theme 和我的插件在样式上不一致导致的**。

绕过方案：
- 禁用 callouts 插件，改用 Typora 自带的功能
- 禁用 Typora 自带的功能，改用 callouts 插件
- 自己手动修改 theme，使得样式统一，就像你做的一样。

## window_tab 样式问题

没太看懂代码 😂，麻烦能解释一下代码的功能吗

下面两段代码是为了样式吗？好像可以直接使用 `:hover` 解决。

```css
div#plugin-window-tab .tab-bar::-webkit-scrollbar{
    display: none!important;
}
div#plugin-window-tab .tab-bar.active::-webkit-scrollbar{
    display: block!important;
}
```
```js
windowNavScroll.addEventListener('mouseenter', () => {
    windowNavScroll.classList.add('active')
})
windowNavScroll.addEventListener('mouseleave', () => {
    windowNavScroll.classList.remove('active')
})
```

下面
```js
```

**Comment by lyidle** [comment]
@obgnail 
感谢提醒，当时没想到可以用hover，也可以用hover悬浮
``` csss
//默认隐藏滚动条
div#plugin-window-tab .tab-bar::-webkit-scrollbar{
    display: none!important;
}
//悬浮显示滚动条
div#plugin-window-tab .tab-bar:hover::-webkit-scrollbar{
    display: block!important;
}
```
第二个是因为要监听write元素，我试过监听窗口时获取offesetWidth总是和实际情况有出入，所以改用ResizeObserver的方法来实现
``` js
// #region 改变滚动条
        const windowNavScroll = document.querySelector('div#plugin-window-tab .tab-bar')
        const windowNavWidth = document.querySelector('#write')
        let ObserverResizeFlag = true
        // 监听窗口变化 是因为窗口大到一定程度后#write的宽不会变化
        window.addEventListener('resize', function () {
            // 节流阀
            if (ObserverResizeFlag) {
                ObserverResizeFlag = false
                // 创建观察对象 实例化ResizeObserver
                // 为了动态的监听#write对象
                const myObserver = new ResizeObserver(entries => {
                    entries.forEach(entry => {
                        console.log('大小位置', entry.contentRect)
                        console.log('监听的DOM', entry.target) 
                        // 多加的margin是因为窗口大到一定程度后#write的宽不会变化 而且不仅有padding 还有margin出现
                        // write的宽度 + 12滚动条宽度 + 左右padding + 左右margin
                        windowNavScroll.style = `width: ${entry.contentRect.width + 12 +
                            +window.getComputedStyle(windowNavWidth).paddingRight.replace('px', '') +
                            +window.getComputedStyle(windowNavWidth).paddingLeft.replace('px', '') +
                            +window.getComputedStyle(windowNavWidth).marginLeft.replace('px', '') +
                            +window.getComputedStyle(windowNavWidth).marginRight.replace('px', '')
                            }px!important;`
                    })
                })
                // 使用ResizeObserver 的observe方法
                myObserver.observe(windowNavWidth)
                setTimeout(() => {
                    // 恢复
                    ObserverResizeFlag = true
                }, 500);
            }
        })
        // #endregion 改变滚动条
```

**Comment by obgnail** [comment]
@lyidle 

使用 ResizeObserver 的实现是不太合理的。

窗口大到一定程度后 `#write` 的宽不会变化，这是因为 theme 写了媒体查询

```css
@media only screen and (min-width: 1800px) {
    #write {
        max-width: 1200px;
    }
}
@media only screen and (min-width: 1400px) {
    #write {
        max-width: 1024px;
    }
}
```

所以上述使用 js 动态修改 `.tab-bar` 的 width 的方式肯定会在某个 theme 下出问题，正确的方法还是使用 CSS 的媒体查询实现。

---

而且我想知道为什么要手动调整 `.tab-bar` 的 width？我觉得默认的 `calc(100vw - var(--sidebar-width, 0));` 很合理呀，你是发现了什么情况下会出现问题吗？

```css
#plugin-window-tab .tab-bar {
    display: flex;
    justify-content: flex-start;
    width: calc(100vw - var(--sidebar-width, 0));
    overflow-x: scroll;
}
```
