### ISSUE TITLE
标题折叠误触发

### ISSUE THREAD

**Issue by LincZero** [obgnail/typora_plugin#738]
标题折叠是否设置了快捷键？为什么我在正文标题上 `Ctrl+V` 有时会误触发标题的折叠，并且我不知道如何快速恢复，只能右键点几次找到展开按钮。

该问题我找不到稳定复现方法，但确实会频繁出现（每天三四次），影响到了我的写作效率。

并且有时连折叠符号都不出现：（如图，复现似乎伴随Ctrl+Z）

![图片](https://github.com/user-attachments/assets/df6ef0e1-105e-4918-9e3f-66283d47a97c)

---

如果短时间未能修复，请告诉我禁用该项插件功能的方法

**Comment by LincZero** [comment]
插件版本 1.10.26
软件版本 1.6.7

**Comment by LincZero** [comment]
Ctrl+数字也会误触发。

我知道了，似乎Ctrl+单击标题就会折叠/展开。

而我操作Ctrl+数字/Ctrl+V时，有时单击操作在Ctrl之后……Ctrl -> 单击 -> V

**Comment by obgnail** [comment]
@LincZero 

1. 如果不喜欢【章节折叠】插件，可以【右键菜单 -> 少用插件 -> 启停插件】取消勾选【章节折叠】
2. 如果觉得 【Ctrl + click】触发过于频繁，可以修改配置文件，改成 ctrl+shift 之类的。

```toml
[collapse_paragraph]
# 各个功能对应的修饰键
#   1. 支持ctrl/alt/shift的随意组合（如"shift+alt"，"ctrl+shift"）
#   2. 但是不能为"alt"（因为alt+click已经被【scrollBookmarker】插件占用），也不能为"shift"（因为shift+click被系统自带的【框选】功能占用）
#   3. 若为""，表示不启用此功能
#   4. 例如【COLLAPSE_SIBLINGS = "ctrl+alt"】：当用户同时按住键盘ctrl和alt，并且鼠标click标题时，会折叠/展开父章节下所有同级的章节
# 功能：
#   - COLLAPSE_SINGLE       ：折叠/展开 单个章节
#   - COLLAPSE_SIBLINGS     ：折叠/展开 父章节下所有同级的章节
#   - COLLAPSE_ALL_SIBLINGS ：折叠/展开 当前文件所有同级的章节
#   - COLLAPSE_RECURSIVE    ：递归折叠/展开 当前章节
MODIFIER_KEY = { COLLAPSE_SINGLE = "ctrl", COLLAPSE_SIBLINGS = "ctrl+alt", COLLAPSE_ALL_SIBLINGS = "ctrl+shift+alt", COLLAPSE_RECURSIVE = "" }
```
