### ISSUE TITLE
插件几个窗口界面显示层级的调整

### ISSUE THREAD

**Issue by at2008** [obgnail/typora_plugin#743]
显示 大纲目录 的情况下，会遮盖 快捷按钮 列表，右键菜单也可能被 大纲目录覆盖；右上角 格式规范检测 按钮也被遮盖了。我简单调整了一下：

```css
/* 大纲目录面板 */
#plugin-toc {
    z-index: 9990;
    height: 95%;
}
/* 快速按钮 */
#plugin-quick-button {
    z-index: 9991;
}
/* 格式规范按钮 */
#plugin-markdownlint-button {
    z-index: 9992 !important;  
}
/* 格式规范列表 */
#plugin-markdownlint {
    z-index: 9993;
}
/* 右键菜单 */
.dropdown-menu {
    z-index: 9998;  
}
```

![image](https://github.com/user-attachments/assets/18fa4031-d7e0-4fd2-bba4-0cef4ce62c5e)

**Comment by obgnail** [comment]
@at2008 

感谢您的贡献，代码已合并，预计明天发版。

此 issue 关闭，如有问题麻烦在下面留言。

**Comment by obgnail** [comment]
@at2008 

[新版本](https://github.com/obgnail/typora_plugin/releases/tag/1.10.31) 已经发布，感谢贡献

**Comment by at2008** [comment]
@obgnail 图片浏览 功能完美 i👍

窗口层级方面，大纲目录 层级 还是 9999，把其他的都遮盖了

```css
.plugin-common-modal {
    z-index: 9999;
}
```
