### ISSUE TITLE
建议添加快捷编辑

### ISSUE THREAD

**Issue by aiqyqy** [obgnail/typora_plugin#76]
1.能否添加代码编辑器一样的快捷编辑，如：
#快速注释
Ctrl+/：注释当前行

#快速删除
Ctrl+X - 删除当前行，相当于剪切

#行移动
Ctrl+Shift+↑ 将光标所在行和上一行代码互换（将光标所在行插入到上一行之前）。 
Ctrl+Shift+↓ 将光标所在行和下一行代码互换（将光标所在行插入到下一行之后）。 

#快速复制
Ctrl+Alt+↓ 复制当前行到下一行(复制增加)
Ctrl+Alt+↑ 复制当前行到上一行(复制增加)

#快速回车
Ctrl+回车  在下方添加一行空行

#快速定位
Ctrl + r    定位到指定函数
Ctrl+q  定位到最后编辑的地方

**Comment by obgnail** [comment]
感谢反馈。

这个需求听起来更像是代码编辑软件需要有的功能。

感觉用户不太会用 Typora 高强度编辑代码。（具体到我的话，都是在 vscode 里复制粘贴到 Typora 的）

**Comment by aiqyqy** [comment]
不只是代码，写文档也需要用到这些的。

**Comment by obgnail** [comment]
@aiqyqy 

你好，当前版本已经添加如下快捷键：

1. 快速删除（Typora 自带）
2. 行移动
3. 快速复制
4. 快速回车

默认快捷键如下，如不喜欢可修改配置：
```toml
# 将当前行和上一行互换
SWAP_PREVIOUS_LINE = "Shift-Alt-Up"
# 将当前行和下一行互换
SWAP_NEXT_LINE = "Shift-Alt-Down"
# 复制当前行到下一行
COPY_PREVIOUS_LINE = "Ctrl-Alt-Up"
# 复制当前行到上一行
COPY_NEXT_LINE = "Ctrl-Alt-Down"
# 直接在下面新建一行
INSERT_LINE_NEXT = "Ctrl-Enter"
# 直接在上面新建一行
INSERT_LINE_PREVIOUS = "Shift-Ctrl-Enter"
```
