### ISSUE TITLE
图片查看优化和中英混排优化的异常问题

### ISSUE THREAD

**Issue by zhonglixun** [obgnail/typora_plugin#769]
这个图片管理可以添加种视图吗？就完全是一堆缩略图列表的显示。
然后就是中英混排优化会把我下划线直接优化没了。我看了下它会在标签内部的两侧额外加上空格就导致下划线被吞了
![PixPin_2024-09-30_21-12-59](https://github.com/user-attachments/assets/489ad6f0-8553-4379-a7d0-89b78a3f7441)
![PixPin_2024-09-30_21-41-18](https://github.com/user-attachments/assets/c1831819-0577-46f1-a417-39be0b4b9f36)

**Comment by obgnail** [comment]
@zhonglixun 

看编辑记录，你好像问了好多问题，一个个来吧

## 中英混排优化

可以通过修改配置文件过滤掉你不想部分

在 settings.user.toml 文件中加入如下内容：

```toml
[md_padding]
# 不希望拆分的正则词组（这些正则内部和前后禁止加空格）
IGNORE_PATTERNS = ["<br\\s*/>", "<u>.+</u>"]
```

## 右下角按钮

如果你想关闭此功能，【右键菜单 -> 少用插件 -> 启停插件 -> 取消勾选快速按钮】

如果你想修改按钮位置或者自定义按钮的功能，**需要你了解 JavaScript**。

具体做法：在 custom_plugin.user.toml 文件中加入如下内容，然后按说明文字修改 buttons 选项

```toml
[quickButton]
[quickButton.config]
# 如果您没有javascript基础，请不要修改以下配置
# 添加的按钮：
#   disable:      禁用此按钮
#   coordinate:   按钮坐标。往上为x轴正方向，往左为y轴正方向，从零开始计数
#   icon:         按钮图标。填入css class。支持font-awesome-4.1.0和ionicons-2.0.1，所有的图标及其对应的css class请参考：https://www.adfwebmagazine.jp/wp-content/uploads/test_v4.1.pdf  和  https://ionic.io/ionicons/v2
#   size(可选):    图标大小。默认17px
#   color(可选):   图标颜色。默认跟随当前主题的配色方案
#   bgColor(可选): 图标背景色。默认跟随当前主题的配色方案
#   hint:         提示信息
#   callback:     回调函数。采用pluginName.MethodName的形式（功能就像hotkey.default.toml中的plugin参数和function参数的合体）
#                     MethodName请通过阅读源码查找。如果您不懂代码，但还是想添加按钮，有个碰运气技巧：在【右键菜单->常用插件->二级插件】的插件基本都是XXX.callback，其余插件基本都是XXX.call
#   evil(危险):    自定义回调函数。功能同hotkey.default.toml中的evil参数（它能用的，这里也能用）。这里的文本内容会被eval()。如果设置此参数，callback参数会失效
buttons = [
    { disable = false, coordinate = [0, 0], hint = "直达底部", size = "24px", icon = "fa fa-caret-down", callback = "go_top.goBottom" },
    { disable = false, coordinate = [1, 0], hint = "直达顶部", size = "24px", icon = "fa fa-caret-up", callback = "go_top.goTop" },
    { disable = false, coordinate = [2, 0], hint = "文字风格", size = "17px", icon = "fa fa-font", callback = "text_stylize.call" },
    { disable = false, coordinate = [3, 0], hint = "混排优化", size = "17px", icon = "fa fa-align-justify", callback = "md_padding.call" },
    { disable = false, coordinate = [0, 1], hint = "思维导图", size = "18px", icon = "fa fa-sitemap", callback = "markmap.onButtonClick" },
    { disable = false, coordinate = [1, 1], hint = "图片管理", size = "17px", icon = "fa fa-image", callback = "imageReviewer.callback" },
    { disable = false, coordinate = [2, 1], hint = "文档大纲", size = "17px", icon = "fa fa-list", callback = "toc.callback" },
    { disable = false, coordinate = [3, 1], hint = "高亮搜索", size = "17px", icon = "fa fa-search", callback = "search_multi.call" },
]
```
