### ISSUE TITLE
自动编号插件里面的attr(data-alt)属性

### ISSUE THREAD

**Issue by George1825** [obgnail/typora_plugin#770]
您好，我看到自动编号插件里面图片自动编号内容里面有一个data-alt属性部分，但是实际图片名字只是Figure 1并没有后面的attr(data-alt)，这个是需要什么其它设置吗，使用了显示图片名字的吗？
谢谢！
![Snipaste_2024-09-30_19-41-11](https://github.com/user-attachments/assets/931247cd-96bb-4047-921f-bc11abeadc49)

**Comment by obgnail** [comment]
@George1825 

你好。

需要将 SHOW_IMAGE_NAME 置为 true。功能就是显示图片名字。

```toml
[auto_number]
ENABLE_IMAGE = true
# 展示图片的名称（若ENABLE_IMAGE为false，此选项失效）
# 注意：不建议开启此选项，会消耗较多资源
SHOW_IMAGE_NAME = true
```

没什么神奇的，不过就是 MutationObserver 动态设置 alt 属性罢了，对应代码 189 行

```js
  if (this.config.ENABLE_IMAGE && this.config.SHOW_IMAGE_NAME) {
      this.utils.eventHub.addEventListener(this.utils.eventHub.eventType.fileEdited, () => {
          const images = this.utils.entities.querySelectorAllInWrite(".md-image:not([data-alt]) > img");
          for (const image of images) {
              image.parentElement.dataset.alt = image.getAttribute("alt");
          }
      })
  }
```
