### ISSUE TITLE
优化建议：标签栏

### ISSUE THREAD

**Issue by jackie-97** [obgnail/typora_plugin#772]
期望每次重新打开软件时，能够记住之前打开的文件，并在标签栏显示

**Comment by obgnail** [comment]
@holwell 

需求已实现。麻烦升级到新版本试用。

目前有两种方式可用：

## 使用 reopenClosedFiles 自动保存并自动打开

> 右键菜单 -> 少用插件 -> 启停插件 -> 勾选【打开上次退出时尚未关闭的标签页（reopenClosedFiles）】

此插件的功能是：会记录最后一次的标签页列表，下次打开的时候会自动恢复

## 使用 window_tab 手动保存和手动打开

1. 第一步，手动保存：右键菜单 -> 少用插件 -> 标签页管理 -> 保存当前标签页列表
2. 第二步，在你希望打开的时候：右键菜单 -> 少用插件 -> 标签页管理 -> 打开保存的标签页列表

---

这两种方法互相独立，你可以同时使用。

**Comment by obgnail** [comment]
需求已实现，此 issue 关闭。

如有问题，麻烦在下面留言或者另开 issue。

**Comment by jackie-97** [comment]
我在typora v1.6.7上，没有复现大佬说的方式1的效果， @obgnail ，这跟typora本身的启动配置有关吗？

**Comment by obgnail** [comment]
@jackie-97 

1. 插件升级到最新版本
2. 需要开启 window_tab 和 reopenClosedFiles 插件
3. 检查插件 reopenClosedFiles 的配置，要求 auto_reopen_when_init 的值为 true，如下：
4. 如果不行，麻烦给个录屏

```toml
[reopenClosedFiles]
# 打开Typora（打开可丢弃的无标题的标签时）自动恢复上次退出时尚未关闭的标签页
# 注意：只当双击typora.exe打开Typora时生效（因为打开特定文件时，自动恢复上次退出时尚未关闭的标签页，明显不符合用户预期）
auto_reopen_when_init = true
```

![bug_report (1)](https://github.com/user-attachments/assets/be99e390-118f-401e-ba97-45590491f0b2)
