### ISSUE TITLE
大纲目录插件显示图片名称

### ISSUE THREAD

**Issue by George1825** [obgnail/typora_plugin#775]
请问在打开自动编号插件的显示图片名称属性后SHOW_IMAGE_NAME = true，可以设置在大纲目录插件中也显示图片名字吗，主要想用来跟他人展示图片方便按名字索引。我还不熟悉js语言，如果不是常见需求，能否帮忙提供一个思路，多谢！

**Comment by George1825** [comment]
测试好用，谢谢！
另外发现下面两个设置好像无效：
这个我设置其它数值，打开的时候宽度不变
width_percent_when_pin_right = 20
这个我修改的时候，发现图片还是以Figure为前缀
show_name = { fence = "Fence", image = "图", table = "Table", link = "Link", math = "Math" }

**Comment by obgnail** [comment]
两项配置同时失效不太可能，盲猜你的配置文件少了 `[toc.config]`。

custom_plugin.xxx.toml 的要求比 settings.xxx.toml 更严格一些。详情请阅读 [readme](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md#%E4%BF%AE%E6%94%B9%E4%BA%8C%E7%BA%A7%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)

```toml
[toc]
[toc.config]
show_name = { fence = "Fence", image = "图", table = "Table", link = "Link", math = "Math" }
```
