### ISSUE TITLE
请问如何修改代码块右上角的图标? 

### ISSUE THREAD

**Issue by 1571312541** [obgnail/typora_plugin#785]
另外,我设置AUTO_HIDE = false不起作用,请问是修改这个文件吗?
![image](https://github.com/user-attachments/assets/87ddbef6-4c6c-4d59-847f-217af03af9ee)

**Comment by obgnail** [comment]
@1571312541 

1. 确实是修改这个文件
2. 因为 `AUTO_HIDE` 的值默认就是 false。你可以试试将其改为 true
3. 我不清楚你说的【修改右上角的图标】具体是什么意思，如果你是想禁用某些按钮，可以修改如下选项（其他选项请查看 `settings.default.toml` 文件）

```toml
[fence_enhance]
# 自动隐藏按钮，鼠标移动到代码块才显示（注意：就算置为true，在折叠状态下的代码块也不会自动隐藏按钮。因为必须提醒用户这个代码块处于折叠状态）
AUTO_HIDE = false
# 启用复制代码功能
ENABLE_COPY = true
# 启用代码调整缩进功能（低版本Typora不可使用此功能）
ENABLE_INDENT = true
# 启用折叠代码功能
ENABLE_FOLD = true
```
