### ISSUE TITLE
功能建议：“文字风格化”功能中添加文字左右对齐和居中功能

### ISSUE THREAD

**Issue by R3c0ger** [obgnail/typora_plugin#835]
我个人的使用场景就是对一整段落加个 `<center></center>` 标签啥的，右对齐都基本没用过，但是居中的话每次想用的时候都总觉得有点麻烦。。。

**Comment by DoubleW2w** [comment]
像这种情况，我的解决方式是在输入法自定义短语 ，比如输入 wbjz 就会出现 `<p style="text-align:center"></p>` 😀，以及一些常用的符号，「」 『』之类的。

**Comment by obgnail** [comment]
@R3c0ger @DoubleW2w 

你好，感谢反馈。

我仔细考虑过了，此功能暂时不做了。抱歉。理由如下：

1. 此需求和【文字风格化】插件难兼容。此插件设计之初只是为了添加文字样式，并没有考虑布局 —— 布局需要占据一整行，属于行盒。而此插件是将文字作为块盒使用的。比如用户框选一行文字的中间部分，此时文字的居中、左右对齐都是做不到的。
2. 此需求比较好的实现方案是类似于 @DoubleW2w 的做法，通过快捷方式快速插入对应的 HTML 标签。此功能可以使用【slash_commands】插件的 snippet 功能实现。

此 issue 关闭，如有问题麻烦在下面留言或者另开 issue。

**Comment by R3c0ger** [comment]
@obgnail OK，这个解决办法最完美。
我之前因为输入顿号也会唤起斜杠命令这个事，直接把插件禁用了，我也不知道当时我为啥没想起来去看看配置，反正后来把这功能忘个一干二净，我说总感觉好像缺了什么很牛逼的功能（笑）

**Comment by R3c0ger** [comment]
@obgnail @DoubleW2w 
另外请问一下，有没有什么办法能实现将光标插在指定位置，比如两个 html 标签的中间？

**Comment by R3c0ger** [comment]
这下爽了，写了一堆 snippet，打造最强编辑器，早看这个 Typora 不爽了。这么牛逼的功能我咋给忘掉了，气死了

**Comment by obgnail** [comment]
> 输入顿号也会唤起斜杠命令

我想你应该也知道，不过还是说明一下。唤起命令的输入是可以自定义的。如果不希望顿号唤起，下面的正则去掉顿号就行了

```toml
[slash_commands]
# 什么样的用户输入触发显示命令列表（若您不了解正则表达式，请勿修改此配置）
#  注意：keyword需要使用命名捕获组kw
#  默认值：匹配一个字符串，该字符串以/或\或、开头，后面紧跟任意数量的非/或\或、字符，且该字符串前面不可有<
TRIGGER_REGEXP = "(?<!<)[\\/、\\\\](?<kw>[^\\/、\\\\]*)$"
```
