### ISSUE TITLE
支持检查升级按钮，比如和官方的帮助模块里面一起，检查插件升级情况，如果有就跳到对应的git去升级（如果合理也可以自动）

### ISSUE THREAD

**Issue by zhainanshidai** [obgnail/typora_plugin#861]
支持检查升级按钮，比如和官方的帮助模块里面一起，检查插件升级情况，如果有就跳到对应的git去升级（如果合理也可以自动）

**Comment by obgnail** [comment]
@zhainanshidai 

已有此功能。【右键菜单 -> 少用插件 -> 升级插件】。

如果想自动升级，可以通过修改配置文件实现。

```toml
[updater]
# 众所周知，有些地区无法裸连github，需要使用代理（如：http://127.0.0.1:7890）
# 若值为空，则将弹出窗口，让用户填入代理；若值不为空，则将直接使用此代理，不再弹出窗口
# 除非你固定使用某代理，否则不建议使用此配置
PROXY = ""
# 是否启用自动静默升级（若为false，则以下配置全部失效）
# 自动升级有两个策略：
#   策略一：打开Typora一段时间后，执行一次升级流程
#   策略二：每隔一段时间，执行一次升级流程
AUTO_UPDATE = false
# 策略一（单位：ms，若<0，则不使用此策略；若<1分钟，则置为1分钟）
START_UPDATE_INTERVAL = 300000   # 1000 * 60 * 5
# 策略二（单位：ms，若<0，则不使用此策略；若<1小时，则置为1小时）
UPDATE_LOOP_INTERVAL = -1
```
