### ISSUE TITLE
【中英文混排优化】希望修复表情内增加空格的bug

### ISSUE THREAD

**Issue by woaiwulima** [obgnail/typora_plugin#896]
Markdown 中包含表情符号，如 :smile: `:smile:`，在使用中英文混排优化时，会导致该符号变为 `: smile:`，从而使表情符号失效，希望修复。

**Comment by obgnail** [comment]
@woaiwulima 

你好，感谢反馈。

你使用的应该是老版本，此问题在新版本中已修复，升级到新版本即可。

此 issue 关闭，如有问题，麻烦在下面留言。

**Comment by woaiwulima** [comment]
我用的是新版啊，发issue之前特意升级过了

**Comment by obgnail** [comment]
@woaiwulima 

那应该是配置文件的问题。

修复步骤如下：

1. 打开文件 `plugin/global/settings/settings.user.toml`
2. 搜索配置 `IGNORE_PATTERNS`，将其改成 `IGNORE_PATTERNS = ["<br\\s*?/?>", ":[0-9a-z_\\-]+?:", "<u>.+?</u>", '<span style=".+?">.+?</span>']`
3. 保存，重启 Typora

最终效果应该类似于：

```toml
[md_padding]
IGNORE_PATTERNS = ["<br\\s*?/?>", ":[0-9a-z_\\-]+?:", "<u>.+?</u>", '<span style=".+?">.+?</span>']

```
