### ISSUE TITLE
auto_number与主题冲突 导致图片编号失效 该怎么修改配置呢

### ISSUE THREAD

**Issue by Doyyyyy** [obgnail/typora_plugin#906]
主题为dtzj：https://github.com/muggledy/typora-dyzj-theme
只有将该功能禁用后才可以恢复图片编号功能
该主题的图片 我使用的是
<img src="" alt="#shadow-blur+gray" style="zoom:100%;"/>
这种代码块插入的。但是配置设置里都设置为false 也无法使用 只有将该功能禁用才可以

**Comment by obgnail** [comment]
@Doyyyyy 

你好，感谢反馈。

图片裂了，麻烦详细说明你的第二个问题

**Comment by obgnail** [comment]
@Doyyyyy 

第一个问题的原因很简单，CSS 冲突了。

![IMG_2024-12-31_12-25-30 (1)](https://github.com/user-attachments/assets/ae298e31-48e4-49ee-9934-94f53db87ed5)

解决方案也很简单，打开 `Typora\themes\source\dyzj.css` 文件，定位到 972 行，将 `#write` 改成 `content`。

```css
#write{
    counter-reset: imgNum;
}
```

修改成：

```css
content{
    counter-reset: imgNum;
}
```
