### ISSUE TITLE
[BUG] 更新到最新版1.12.5后自定义快捷键全部失效

### ISSUE THREAD

**Issue by Zxis233** [obgnail/typora_plugin#934]
配置文件未更改，前一版本正常，在更新到1.12.5后，`plugin\global\settings`下的`hotkey.*.toml`会在Typora启动后被自动删除。请问如何排查问题？

**Comment by obgnail** [comment]
@Zxis233 

你好，感谢反馈。

原先的二级插件 `hotkeyHub` 迁移为 一级插件 `hotkeys`。同时干掉了 `hotkey.*.toml` 文件，将其移动到 `settings.user.toml` 的 hotkeys 插件的 `CUSTOM_HOTKEYS` 选项中，麻烦检查一下。

---

以下是我的配置，供参考：

```toml
[[hotkeys.CUSTOM_HOTKEYS]]
enable = true
hotkey = "ctrl+alt+n"
desc = "快速插入代码块"
evil = '() => this.utils.insertFence("javascript")'

[[hotkeys.CUSTOM_HOTKEYS]]
enable = true
hotkey = "ctrl+alt+l"
desc = "当光标置于代码块中，按下此快捷键可以调整缩进代码块"
plugin = "fence_enhance"
function = "indentFence"
closestSelector = "#write .md-fences"

[[hotkeys.CUSTOM_HOTKEYS]]
enable = true
hotkey = "-"
desc = "自动最大化"
evil = "() => console.log('enterFullscreen'); this.utils.eventHub.addEventListener(this.utils.eventHub.eventType.allPluginsHadInjected, () => document.getElementById('w-max').dispatchEvent(new MouseEvent('mouseup', { which: 1 })))"
"""
```
