### ISSUE TITLE
无法打出中文右括号

### ISSUE THREAD

**Issue by Sakanako2333** [obgnail/typora_plugin#938]
使用shift + enter换行的行中，打中文右括号的时候会直接自动变成英文括号

**Comment by obgnail** [comment]
@Sakanako2333 

你好，感谢反馈。

我在 Typora 0.9.98 和 1.9.5 都无法复现你的情况。

你是开启了 chineseSymbolAutoPairer 插件的 auto_swap 功能吗？这个插件会自动将连续两个中文符号合并为一个英文符号。

```toml
[chineseSymbolAutoPairer]
# 连续输入两个相同的中文标点符号，转为对应的英文标点符号（双全角标点合成一个半角标点）
#   true:  启用此行为
#   false: 关闭此行为
auto_swap = false
```

如果不是这个问题，麻烦尝试关闭 chineseSymbolAutoPairer 插件，看问题是否解决。

如果可以的话，麻烦录一下屏，协助我排查。
