### ISSUE TITLE
支持按自定义代码行数折叠代码块

### ISSUE THREAD

**Issue by liushupeng** [obgnail/typora_plugin#939]
当前支持了默认折叠代码块的功能，希望能够增加可以自定义代码行数，来决定是否折叠代码块。

1. 像10行以内的短小代码，不折叠效果更好；几十行的代码折叠起来更好。具体行数的阈值可以自定义。
2. 在1的基础上可以更进一步，如果一共40行代码，而设置的折叠行数是10，不是40行全折叠，而是只折叠11~40行。全折叠还是部分折叠可以由开关控制

**Comment by obgnail** [comment]
@liushupeng 

你好，感谢反馈。

第一个需求已实现。 代码在 master 分支中，等待发版。

新增了 `DEFAULT_FOLD_THRESHOLD` 选项：开启默认折叠后，仅当代码块行数大于此值时才会被默认折叠

```toml
[fence_enhance]
# 代码块折叠行数：开启默认折叠后，仅当代码块行数大于此值时才会被默认折叠
#   设置为 0 则所有代码块都会被折叠
DEFAULT_FOLD_THRESHOLD = 0
```

第二个需求决定暂时不做了，抱歉。理由是：

- 状态太多了，用户心智负担较重。
- 插件 `代码块增强` 是支持用户自定义按钮的，有需要的话，您可以通过设置 CUSTOM_BUTTONS 配置选项实现自己的按钮。


```toml
[fence_enhance]
# 自定义按钮：允许用户添加自定义按钮到代码块，进行更高级的操作（高级配置，需要一定的 JavaScript 基础）
#   DISABLE: 是否禁用此按钮
#       true:  禁用此按钮，不显示在代码块上
#       false: 启用此按钮，显示在代码块上
#   ICON: 按钮图标的 CSS class
#       支持 Font Awesome 4.1.0 的图标，参考：https://www.adfwebmagazine.jp/wp-content/uploads/test_v4.1.pdf
#       例如: "fa fa-bomb"
#   HINT: 鼠标悬停在按钮上时显示的功能提示
#   ON_INIT: 初始化函数字符串，此函数只在插件初始化时执行一次
#       参数: plugin - 插件实例对象
#       示例: "plu => console.log('custom fence button has init')"，不需要则置为空字符串 ""
#   ON_RENDER: 渲染后回调函数字符串，每次页面渲染代码块时都会执行此函数
#       参数: buttonElement - 按钮的 DOM 元素对象
#       示例: "btn => console.log('btn has render')"，不需要则置为空字符串 ""
#   ON_CLICK: 鼠标点击按钮时的回调函数字符串，点击时执行此函数
#       参数: {ev, btn, cont, fence, cid, plu}，分别表示：click 事件对象，按钮的 DOM 元素对象，代码块文本内容，代码块的 DOM 元素对象，代码块的 CID，插件实例对象
#       示例: "({cont}) => console.log(cont)"。此项不可为空
CUSTOM_BUTTONS = [
    { DISABLE = true, ICON = "fa fa-bomb", HINT = "demo", ON_INIT = "", ON_RENDER = "", ON_CLICK = "({cont}) => console.log(cont)" },
]
```

---

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
