### ISSUE TITLE
自动编号能添加一个常用的样式，可以不同样式切换

### ISSUE THREAD

**Issue by gdqb521** [obgnail/typora_plugin#948]
默认的多级编号满足基本的层级需求，但是有些文档，要求按正规格式编号，例如下面这个编号格式：
第一层为汉字数字加顿号，例如：“一、”“二、”“三、”；
第二层为括号中包含汉字数字，后面不能再加“、”或“，”，例如：“（一）”“（二）”“（三）”；
第三层为阿拉伯数字加下脚点，例如：“1. ”“2.”“3.”；
第四层为括号中包含阿拉伯数字，后面不能再加“、”或“，”，例如：“（1）”“（2）”“（3）”；
第五层为带圈的阿拉伯数字，例如：“①”“②”“③”或者“1）”“2）”“3）”；
第六层为大写英文字母，例如：“A.”“B.”“C.”或者“（A）”“（B）”“（C）”；
第七层为小写英文字母，例如： “a.”“b.”“c.”或者“（a)”“（b）”“（c)”；
第八层为罗马数字：I——1、II——2、III——3、IV——4、V——5、VI——6、VII——7、VIII——8、IX——9、X——10、XI——11、XII——12、XIII——13、XIV——14、XV——15、XVI——16、XVII——17、XVIII——18、XIX——19、XX——20。
这种自动编号，能否适配，但是原来的多级编号的样式也保留，用户可以现在自动编号样式，以满足不同文档的格式要求。
或者如何自定义添加一个规范格式？

**Comment by obgnail** [comment]
你好，感谢反馈。

需求已实现，代码在 master 分支中。

auto_number 新增了 `LAYOUTS` 选项，用以自定义编号格式。目前内置了两种编号格式：`Decimal` 和 `CJK`。

![Image](https://github.com/user-attachments/assets/448252ac-e4c1-4b2c-8039-eac763b9bec9)

其中 `Decimal` 为默认的编号格式。`CJK` 为国内学位论文的编号格式：

```
二级标题：一、
三级标题：（二）
四级标题：1.
五级标题：（1）
六级标题：1）
```

**Comment by obgnail** [comment]
@gdqb521 

需求已实现，此 issue 关闭，如有使用上的问题，麻烦下面留言，或者另开 issue。

**Comment by gdqb521** [comment]
cjk中，表格的编号一般要在表格的上方，图的编号一般要求在图的下方。
这个编号后方，是否可以添加题注，就是对图表的说明文字

可以设置几级标题参与编号也是个实际应用的一种情况，当然更多的是你不设置这一级标题，也就不是问题了。实际情况是需要根据规范要求，定义不同级别标题的样式和级别编号，情况也较为复杂。
一级标题编号在章节编号中也有需求，例如一级标题代表第几章，二级标题开始是第几节等等。

**Comment by obgnail** [comment]
@gdqb521 

你好，感谢反馈。需要已实现，代码于 master 分支中。

1. 表格编号位置问题，已实现。新增配置参数了 POSITION_TABLE
2. 表格的题注。不实现。抱歉。原因：Markdown 语法不支持。拒绝方言，我希望所有的插件都遵守 [CommonMark](https://commonmark.org/)，这样不会绑架用户，用户可以毫无负担地卸载 typora_plugin。但是图片是支持题注的，你可以降配置参数 SHOW_IMAGE_NAME 置为 true。
3. 一级标题编号，已实现。目前 CJK 的编号格式如下。我查了规定，h3-h6 要缩进两位，于是加了 `\A0`

```toml
[[auto_number.LAYOUTS]]
# 布局名称，用于标识不同的布局
name = "Layout::CJK"
# 是否选中此布局。如果为 true，则使用此布局的编号格式。
selected = false
# 布局的具体设置
[auto_number.LAYOUTS.layout]
content-h1 = "{c1:cjk}、"
content-h2 = "（{c2:cjk}）"
content-h3 = "\\A0\\A0{c3}."    # \A0 表示空格
content-h4 = "\\A0\\A0（{c4}）"
content-h5 = "\\A0\\A0{c5}）"
content-h6 = "\\A0\\A0{c6:ua}."

outline-h1 = "{o1:cjk}、"
outline-h2 = "（{o2:cjk}）"
outline-h3 = "{o3}."
outline-h4 = "（{o4}）"
outline-h5 = "{o5}）"
outline-h6 = "{o6:ua}."

toc-h1 = "{t1:cjk}、"
toc-h2 = "（{t2:cjk}）"
toc-h3 = "{t3}."
toc-h4 = "（{t4}）"
toc-h5 = "{t5}）"
toc-h6 = "{t6:ua}."

table = "表 {t}"
image = "图 {i}"
fence = "代码 {f}"
```
