### ISSUE TITLE
自动编号功能优化建议

### ISSUE THREAD

**Issue by shuaeo** [obgnail/typora_plugin#950]
自动编号功能优化建议：

1. 大纲、正文、TOC 三者的自动编号应该是一体的，要么都开启要么都关闭，在右键菜单设置中只保留一个是不是更好（或者增加一个总开关）。
2. 希望能够提供关于一级编号样式的更多选择：
   - 一级编号使用汉字一二三四，后面跟顿号，可通过修改 [counter()](https://developer.mozilla.org/zh-CN/docs/Web/CSS/counter) 样式实现：`counter(h2, cjk-ideographic)`
   - 一级编号使用数字，前面补零实现对齐，在章节较多时将更加美观：`counter(h2, decimal-leading-zero)`
   - 一级编号使用数字，但是后面不加圆点，和其他各级编号保持一致。
3. 一般编号到三级就可以了，希望可以提供相应的配置项来让用户自由决定编号的深度（甚至是标题在大纲和 TOC 中显示的深度）。
4. 希望可以选择从 h1 还是 h2 开始编号。
5. 现在的编号通过 CSS 实现，不具备跨平台性。希望增加一键硬编号功能，可以在完稿后添加实际的编号。

仅供参考，作者可以选择实现。谢谢！

**Comment by obgnail** [comment]
@shuaeo 

你好，感谢反馈。

很巧，今天刚实现这个需求。刚关闭了一个需求，你就提一个新的了。请右转 #948 

## 建议一

分开总比合并好，多一个控制变量也不会吃米。

## 建议二、三

今天刚实现，代码在 master 分支中。

现在你可以通过修改配置文件，**为任何元素决定任何编号规则**。

详见  #948 

核心实现函数在这里：

https://github.com/obgnail/typora_plugin/blob/ece937f5ff918314bd020eb616f24f61760283f3/plugin/auto_number.js#L279

## 建议四

影响的地方挺多的，我还没想好要怎么做。

## 建议五

在今天的更新后，插件已经支持用户使用 CSS 函数 `counter(counterName, counterStyle)` 的第二参数 counterStyle 了。如果要硬编码，可能要使用 JS 把 counterStyle 全部实现一遍……好痛苦。

**Comment by obgnail** [comment]
@shuaeo 

相同问题，此 issue 关闭。如有问题，麻烦到 #948 讨论。

**Comment by obgnail** [comment]
@shuaeo 

你好，感谢反馈。已支持 h1 编号，代码于 master 分支中。

目前有两个 Layout，`Layout::Decimal` 是从 h2 编号，`Layout::CJK` 是从 h1 编号。

**Comment by shuaeo** [comment]
谢谢，很好用。不过在导出为 PDF 时书签的编号还是原来的样式，这个有办法同步修改吗？

另外附上我的配置，可以完美实现上面提到的需求，以供后来者参考：

```toml
[auto_number]
ENABLE_TABLE = false
ENABLE_IMAGE = false
ENABLE_FENCE = false

  [[auto_number.LAYOUTS]]
  name = "Layout::h2 一、 1.1 1.1.1"
  selected = true

    [auto_number.LAYOUTS.layout]
    content-h1 = ""
    content-h2 = "{c2:cjk}、 "
    content-h3 = "{c2}.{c3} "
    content-h4 = "{c2}.{c3}.{c4} "
    outline-h1 = ""
    outline-h2 = "{o2:cjk}、 "
    outline-h3 = "{o2}.{o3} "
    outline-h4 = "{o2}.{o3}.{o4} "
    toc-h1 = ""
    toc-h2 = "{t2:cjk}、 "
    toc-h3 = "{t2}.{t3} "
    toc-h4 = "{t2}.{t3}.{t4} "
    table = "表 {t}"
    image = "图 {i}"
    fence = "代码 {f}"

  [[auto_number.LAYOUTS]]
  name = "Layout::h2 01 1.1 1.1.1"
  selected = false

    [auto_number.LAYOUTS.layout]
    content-h1 = ""
    content-h2 = "{c2:dlz} "
    content-h3 = "{c2}.{c3} "
    content-h4 = "{c2}.{c3}.{c4} "
    outline-h1 = ""
    outline-h2 = "{o2:dlz} "
    outline-h3 = "{o2}.{o3} "
    outline-h4 = "{o2}.{o3}.{o4} "
    toc-h1 = ""
    toc-h2 = "{t2:dlz} "
    toc-h3 = "{t2}.{t3} "
    toc-h4 = "{t2}.{t3}.{t4} "
    table = "表 {t}"
    image = "图 {i}"
    fence = "代码 {f}"

  [[auto_number.LAYOUTS]]
  name = "Layout::h1 一、 1.1 1.1.1"
  selected = false

    [auto_number.LAYOUTS.layout]
    content-h1 = "{c1:cjk}、 "
    content-h2 = "{c1}.{c2} "
    content-h3 = "{c1}.{c2}.{c3} "
    outline-h1 = "{o1:cjk}、 "
    outline-h2 = "{o1}.{o2} "
    outline-h3 = "{o1}.{o2}.{o3} "
    toc-h1 = "{t1:cjk}、 "
    toc-h2 = "{t1}.{t2} "
    toc-h3 = "{t1}.{t2}.{t3} "
    table = "表 {t}"
    image = "图 {i}"
    fence = "代码 {f}"

  [[auto_number.LAYOUTS]]
  name = "Layout::h1 01 1.1 1.1.1"
  selected = false

    [auto_number.LAYOUTS.layout]
    content-h1 = "{c1:dlz} "
    content-h2 = "{c1}.{c2} "
    content-h3 = "{c1}.{c2}.{c3} "
    outline-h1 = "{o1:dlz} "
    outline-h2 = "{o1}.{o2} "
    outline-h3 = "{o1}.{o2}.{o3} "
    toc-h1 = "{t1:dlz} "
    toc-h2 = "{t1}.{t2} "
    toc-h3 = "{t1}.{t2}.{t3} "
    table = "表 {t}"
    image = "图 {i}"
    fence = "代码 {f}"

  [[auto_number.LAYOUTS]]
  name = "Layout::Decimal"
  selected = false

    [auto_number.LAYOUTS.layout]
    content-h1 = ""
    content-h2 = "{c2}. "
    content-h3 = "{c2}.{c3} "
    content-h4 = "{c2}.{c3}.{c4} "
    content-h5 = "{c2}.{c3}.{c4}.{c5} "
    content-h6 = "{c2}.{c3}.{c4}.{c5}.{c6} "
    outline-h1 = ""
    outline-h2 = "{o2}. "
    outline-h3 = "{o2}.{o3} "
    outline-h4 = "{o2}.{o3}.{o4} "
    outline-h5 = "{o2}.{o3}.{o4}.{o5} "
    outline-h6 = "{o2}.{o3}.{o4}.{o5}.{o6} "
    toc-h1 = ""
    toc-h2 = "{t2}. "
    toc-h3 = "{t2}.{t3} "
    toc-h4 = "{t2}.{t3}.{t4} "
    toc-h5 = "{t2}.{t3}.{t4}.{t5} "
    toc-h6 = "{t2}.{t3}.{t4}.{t5}.{t6} "
    table = "Table {t}"
    image = "Image {i}"
    fence = "Fence {f}"
```

在不同 Layout 之间切换时可能会出现编号错乱，重启软件即可恢复正常。

**Comment by obgnail** [comment]
@shuaeo 

你好，感谢反馈。

1. 导出 PDF 需要用到 JS，不是纯 CSS 实现，所以需要额外单独实现，目前还不行。
2. `Layout 之间切换时可能会出现编号错乱` 这个问题是由于您的配置选项不全导致的。

如下配置，**需要补全 content-h4 ~ content-h6，outline-h4 ~ outline-h6，toc-h4 ~ toc-h6**。如果不需要编号，全部置为 `""` 即可。但是不能不写。其他同理。

> 不写的含义是使用上次 Layout 的值。

```toml
    content-h1 = "{c1:dlz} "
    content-h2 = "{c1}.{c2} "
    content-h3 = "{c1}.{c2}.{c3} "
    outline-h1 = "{o1:dlz} "
    outline-h2 = "{o1}.{o2} "
    outline-h3 = "{o1}.{o2}.{o3} "
    toc-h1 = "{t1:dlz} "
    toc-h2 = "{t1}.{t2} "
    toc-h3 = "{t1}.{t2}.{t3} "
    table = "表 {t}"
    image = "图 {i}"
    fence = "代码 {f}"
```
