### ISSUE TITLE
是否能添加警告框的快捷键？

### ISSUE THREAD

**Issue by huangcancan-xbc** [obgnail/typora_plugin#951]
![Image](https://github.com/user-attachments/assets/c26e2874-eb27-4cf4-a40d-992668248ac2)

请问一下，这个警告框可不可以自定义快捷键？

**Comment by obgnail** [comment]
@huangcancan-xbc 

你好，感谢反馈。**任何功能都支持自定义快捷键。**

打开配置文件 settings.user.toml，写入如下内容，之后就可以使用 ctrl+alt+n 插入 callout 了。

```toml
[hotkeys]
# 参数说明:                                                                                                
#   desc:            描述。可填写任意内容，对功能没有影响                                                                
#   enable:          是否启用此快捷键                                                                          
#   hotkey:          快捷键组合                                                                             
#   plugin:          调用的插件名称                                                                           
#   function:        调用插件的函数名                                                                          
#   closestSelector: 定位到当前光标的父元素，并将其作为参数传入 function。如果 function 没有参数，则不需要此选项                           
#   evil:            自定义回调函数，这里的文本内容会被 `eval()`。如果设置此参数，那么参数 plugin、function、closestSelector 都会失效      
CUSTOM_HOTKEYS = [
    { enable = true, hotkey = "ctrl+alt+n", desc = "插入Callouts", evil = '() => File.editor.stylize.insertAlert("TIP")' },
]
```
