### ISSUE TITLE
关于slash_commands的反馈2：获取当前行文字作为插入内容

### ISSUE THREAD

**Issue by wangbenchong** [obgnail/typora_plugin#961]
上次反馈的控制游标位置（即cursorOffset）很受用，自己尝试做了个指令：

[[slash_commands.COMMANDS]]
enable = true
type = "snippet"
icon = "👕"
hint = "以上（箭头）"
keyword = "ArrowUp"
cursorOffset = [ -6, -4 ]
callback = "↑↑ *以上* ↑↑"

然后我可以把剪切板的文字粘贴替换“以上”这两个字。
不过还是不够方便，我希望能**获取当前行的文字，自动替换“以上”这两个字**。

刚体验了新版1.13.4，感觉gen-snp真的是神秘而又强大，不过目前我还不会自己定制，也许已经能实现这个功能只是我还不会用~

**Comment by obgnail** [comment]
@wangbenchong 

你好，感谢反馈。没听懂，麻烦详细描述你的需求。

**Comment by obgnail** [comment]
是这样吗？

不能只写入 `/`，必须设计一个 replace 函数，然后以 `_` 分隔：

![Image](https://github.com/user-attachments/assets/778a05a9-80f1-442b-9425-13cdedd63ff4)

**Comment by wangbenchong** [comment]
对就是这个，刚开始我就觉得现有的gen-snp能做到，只是我自己不大会写代码，得学习一下。

**Comment by wangbenchong** [comment]
分享一下我用粗浅代码之前处理markdown的方法：[我的一个github文章](https://github.com/wangbenchong/doc/blob/main/%E5%B7%A5%E5%85%B7/C%23%E5%B7%A5%E5%85%B7%E9%9B%86/C%23_%E4%BB%A5markdown%E5%BD%A2%E5%BC%8F%E5%88%97%E5%87%BA%E6%89%80%E6%9C%89cs%E6%96%87%E4%BB%B6.md)

**Comment by obgnail** [comment]
我更新了代码，代码在 master 分支中。

1. 首先你要拉取 master 代码，更新插件
2. 在 user.toml 添加如下命令，我写了两个，一个 insert，另一个 replace
3. insert 是在前面插入 `abc你好def你好gh`，replace 是先删除后面的`你好`，然后在插入。所以前者的结果是 `abc你好def你好gh你好`，后者的结果是 `abc你好def你好gh`

```toml
[[slash_commands.COMMANDS]]
enable = true
type = "gen-snp"
icon = "🌟"
keyword = "insert"
callback = "(text) => 'abc@def@gh'.replace(/@/g, this.inputs.textAfter)"

[[slash_commands.COMMANDS]]
enable = true
type = "command"
icon = "🌟"
keyword = "replace"
callback = """
(text) => {
    const cnt = 'abc@def@gh'.replace(/@/g, this.inputs.textAfter)
    const { range, bookmark } = this.utils.getRangy()
    bookmark.start = 0
    bookmark.end += this.inputs.textAfter.length
    range.moveToBookmark(bookmark)
    range.deleteContents()
    this.utils.insertText(null, cnt, false)
}
"""
```

**Comment by obgnail** [comment]
btw，你可以通过 `this.inputs` 获取文字信息。他是一个如下的 object

```json
{
    "kw": "",
    "textBefore": "",
    "textAfter": "",
    "scope": "", 
    "bookmark": null
}
```

![Image](https://github.com/user-attachments/assets/acb5b441-1daa-495c-b155-1bc1b56e4a8d)

**Comment by obgnail** [comment]
顺便一说，其实不更新代码也可以。

你可以使用 text 代替 this.inputs.textAfter（text 是 `_` 后面的文字）。只是更新后可以通过 `this.inputs` 获取更多的信息。

---

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by wangbenchong** [comment]
之前用command做的replace我试了最符合我目前的需求【斜杠在行首】，我想结合你给的textAfter把功能改成【斜杠在行的任意位置】，发现不是很好改，首先要去掉textBefore中最后一个斜杠及后面的字符。但是在计算bookmark范围的时候发现怎样改start和end都无法删除原有整行。

**Comment by wangbenchong** [comment]
很神奇的我改好了

```js
[[slash_commands.COMMANDS]]
enable = true
type = "command"
icon = "🌟"
hint = "上（箭头）"
cursorOffset = [ -4, -4 ]
keyword = "ArrowUp"
callback = """
(text) => {
    // 去掉 textBefore 中最后一个斜杠及其之后的所有字符
    const lastSlashIndex = this.inputs.textBefore.lastIndexOf('/');
    const textBefore = lastSlashIndex !== -1
        ? this.inputs.textBefore.slice(0, lastSlashIndex)
        : this.inputs.textBefore;

    // 获取斜杠前后的内容，拼接成整行内容
    const fullText = textBefore + this.inputs.textAfter;

    // 构造替换后的内容，支持多次替换
    const cnt = '↑↑ *@* ↑↑'.replace(/@/g, fullText);

    // 获取当前行的范围
    const { range, bookmark } = this.utils.getRangy();

    // 调整范围
    bookmark.start = 0;
    bookmark.end += this.inputs.textAfter.length;

    // 删除原有内容
    range.moveToBookmark(bookmark);
    range.deleteContents();

    // 插入新内容
    this.utils.insertText(null, cnt, false);
}
"""
```

不过还是不大理解为什么改好了

**Comment by obgnail** [comment]
@wangbenchong 

我发现你把 cursorOffset 设置成了 `[ -4, -4 ]`，应该是想把光标移动到 `*` 前面。

实际上这是不行的，因为你插入了斜体文字，斜体的内容被单独设置成了一个标签，已经不在同一个 TextNode 里面了。

此时不应该使用 cursorOffset 了，需要自己计算并漂移光标。

我写了一个简易的代码供你参考。我在最后等待了 150ms，然后漂移光标。我的写得很脏，需要你自己修改得更加健壮。

具体的光标漂移知识请参考：

- [mozilla-Selection](https://developer.mozilla.org/zh-CN/docs/Web/API/Selection)
- [mozilla-Range](https://developer.mozilla.org/zh-CN/docs/Web/API/Range)

```toml
[[slash_commands.COMMANDS]]
enable = true
type = "command"
icon = "🌟"
hint = "上（箭头）"
keyword = "ArrowUp"
callback = """
(text) => {
    // 去掉 textBefore 中最后一个斜杠及其之后的所有字符
    const lastSlashIndex = this.inputs.textBefore.lastIndexOf('/');
    const textBefore = lastSlashIndex !== -1
        ? this.inputs.textBefore.slice(0, lastSlashIndex)
        : this.inputs.textBefore;

    // 获取斜杠前后的内容，拼接成整行内容
    const fullText = textBefore + this.inputs.textAfter;

    // 构造替换后的内容，支持多次替换
    const cnt = '↑↑ *@* ↑↑'.replace(/@/g, fullText);

    // 获取当前行的范围
    const { range, bookmark } = this.utils.getRangy();

    // 调整范围
    bookmark.start = 0;
    bookmark.end += this.inputs.textAfter.length;

    // 删除原有内容
    range.moveToBookmark(bookmark);
    range.deleteContents();

    // 插入新内容
    this.utils.insertText(null, cnt, false);

    // 光标漂移
    setTimeout(() => {
        const { range, bookmark } = this.utils.getRangy()
        const target = [...bookmark.containerNode.childNodes].findLast(e => e.classList.contains("md-pair-s"))
        target.classList.add("md-expand")
        const mark = target.querySelector(".md-meta.md-after").previousElementSibling
        range.setStartAfter(mark)
        range.setEndAfter(mark)
        range.select()
    }, 150)
}
"""
```

![Image](https://github.com/user-attachments/assets/5afe8932-8515-451c-be28-56210cac9678)

**Comment by wangbenchong** [comment]
感谢对于【光标漂移】的讲解，我在学习js中（之前的代码也是ai协助的）。目前cursorOffset能满足空行时的情况，所以还算满足需求，不过确实不够完美。感觉这套代码足够合理的话可以抽成一个函数（不知道用户配置能不能存公共代码块），因为最后只有传入的字符串'↑↑ *@* ↑↑'有可能变更。

**Comment by obgnail** [comment]
这些都可以实现，但是暂时不做。不想再多加机制了。

---


> '↑↑ _@_ ↑↑'有可能变更

不需要多条命令，你可以将变化封装为函数参数呀。

`/TableGenerator_3_4` 即可插入三列四行的表格。

```toml
[[slash_commands.COMMANDS]]
enable = true
type = "command"
icon = "🌟"
keyword = "TableGenerator"
callback = """
(col, row) => { 
	col = parseInt(col);     // TableGenerator_3_4 里的 3 和 4 会作为 col 和 row 传入
	row = parseInt(row); 
	const c = ['      ', ' ---- ', ...Array(row - 1).fill('      ')]
		.map(e => `|${Array(col).fill(e).join('|')}|`)
		.join('\\n'); 
	this.utils.insertText(null, c, false)
}
"""
```


你目前的 ArrowUp 命令没有处理参数，你完全可以通过 `/ArrowUp_up`，`/ArrowUp_down` 进行调用：

```toml
[[slash_commands.COMMANDS]]
enable = true
type = "command"
icon = "🌟"
hint = "上（箭头）"
keyword = "ArrowUp"
callback = """
(params) => {
    const d = params[0]
    if (d === "up") {}
}
"""
```
