### ISSUE TITLE
代码块的自动编号，名称是否可以自行编辑？

### ISSUE THREAD

**Issue by CloverAn** [obgnail/typora_plugin#968]
如题，代码块是可以自动编号的，请问这个地方是否允许自行编辑名称？很多代码块的时候可以做到分类描述

![Image](https://github.com/user-attachments/assets/3222d0c9-d829-45bf-a6e0-9709c7ddd5fe)

**Comment by obgnail** [comment]
@CloverAn 

1. 可以自行编辑统一的编号格式（比如 `Fence 7` 改成 `BlockCode 7`），你需要修改 auto_number 的 LAYOUTS 配置。
2. 但是不支持为每个代码块设置自己的描述文本，这超出了 [CommonMark](https://commonmark.org/) 的语法能力，需要引入自定义语法才能实现。

```toml
[auto_number]
# ------------------- 编号格式 -------------------
# 编号格式定义：
#   你可以在这里自定义不同元素的编号格式，支持的元素类型包括：
#     - content-h1 ~ content-h6:  正文内容中的一级标题到六级标题
#     - outline-h1 ~ outline-h6:  大纲视图中的一级标题到六级标题
#     - toc-h1 ~ toc-h6:          TOC 中的一级标题到六级标题
#     - table:                    表格
#     - image:                    图片
#     - fence:                    代码块
#
# 编号格式语法：
#   借鉴了 Python 的 f-string 语法，它能让你轻松地组合文本和计数器。
#   格式如下：
#     "前缀{计数器名称:计数样式}后缀"
#   例如：
#     image = "图{i:cjk}"
#   最终的图片编号是：
#     图一, 图二, 图三, ...
#   解释：
#     - "图" 是前缀，表示编号前显示的文字
#     - {i:cjk} 是编号的核心：
#       - i 是计数器名称，代表“图片”的计数器
#       - cjk 是计数样式，表示使用中文数字 (一, 二, 三, ...)
#     - 后缀为空，表示编号后没有文字
#
#   组合多个计数器：
#     你可以组合多个计数器和文本，创建复杂的编号格式
#     例如：content-h4 = "{c2:ua}-{c3:cjk}.{c4:ur}"
#     如果当前是：第 2 个二级标题，第 5 个三级标题，第 3 个四级标题，那么最终的四级标题编号会是：`B-五.III`
#     解释：
#       - {c2:ua} 表示使用大写英文字母计数二级标题 (A, B, C...)，结果为 B
#       - {c3:cjk} 表示使用中文数字计数三级标题 (一, 二, 三...)，结果为 五
#       - {c4:ur} 表示使用大写罗马数字计数四级标题 (I, II, III...)，结果为 III
#
# 计数器名称：
#   - c1 ~ c6: 分别用于正文中 1 级到 6 级标题
#   - o1 ~ o6: 分别用于大纲中 1 级到 6 级标题
#   - t1 ~ t6: 分别用于目录中 1 级到 6 级标题
#   - t: 用于表格的计数
#   - i: 用于图片的计数
#   - f: 用于代码块的计数
#
# 可用的计数样式：
#   - d:   阿拉伯数字 (1, 2, 3, 4, ...)        *默认值。{c2:d}可以省略为{c2}*
#   - dlz: 前导零的阿拉伯数字 (01, 02, 03, 04, ...)
#   - lr:  小写罗马数字 (i, ii, iii, iv, v, ...)
#   - ur:  大写罗马数字 (I, II, III, IV, V, ...)
#   - la:  小写英文字母 (a, b, c, d, ...)
#   - ua:  大写英文字母 (A, B, C, D, ...)
#   - lg:  小写希腊字母 (α, β, γ, δ, ...)
#   - hs:  天干 (甲, 乙, 丙, 丁, ...)
#   - eb:  地支 (子, 丑, 寅, 卯, ...)
#   - cjk: 汉字数字 (一, 二, 三, 四, ...)
#   - scf: 简体中文大写数字 (壹, 贰, 叁, 肆, ...)  *注意：仅 Typora 新版本支持*
#   - tcf: 繁体中文大写数字 (壹, 贰, 參, 肆, ...)  *注意：仅 Typora 新版本支持*
#   - jf:  日文汉字大写数字 (壱, 弐, 参, 肆, ...)  *注意：仅 Typora 新版本支持*
#   - hi:  平假名 (あ, い, う, ...)             *注意：仅 Typora 新版本支持*
#   - ka:  片假名 (ア, イ, ウ, ...)             *注意：仅 Typora 新版本支持*
#   - di:  实心圆点 (●)
#   - ci:  空心圆点 (○)
#   - sq:  实心方块 (■)
#   - no:  无 (不显示编号)

# 布局：
#   你可以定义多个布局，并选择一个作为当前使用的布局
#   每个布局都包含了一套完整的编号格式定义。若某一元素不需要编号，请置为 ""
# 布局配置：
#   - name: 布局名称，用于标识不同的布局
#   - selected: 是否选中此布局。若为 true，则使用此布局的编号格式
#   - layout: 布局的具体设置
[[auto_number.LAYOUTS]]
name = "Layout::Decimal-H1"
selected = false
[auto_number.LAYOUTS.layout]
content-h1 = "{c1}. "
content-h2 = "{c1}.{c2} "
content-h3 = "{c1}.{c2}.{c3} "
content-h4 = "{c1}.{c2}.{c3}.{c4} "
content-h5 = "{c1}.{c2}.{c3}.{c4}.{c5} "
content-h6 = "{c1}.{c2}.{c3}.{c4}.{c5}.{c6} "
outline-h1 = "{o1}. "
outline-h2 = "{o1}.{o2} "
outline-h3 = "{o1}.{o2}.{o3} "
outline-h4 = "{o1}.{o2}.{o3}.{o4} "
outline-h5 = "{o1}.{o2}.{o3}.{o4}.{o5} "
outline-h6 = "{o1}.{o2}.{o3}.{o4}.{o5}.{o6} "
toc-h1 = "{t1}. "
toc-h2 = "{t1}.{t2} "
toc-h3 = "{t1}.{t2}.{t3} "
toc-h4 = "{t1}.{t2}.{t3}.{t4} "
toc-h5 = "{t1}.{t2}.{t3}.{t4}.{t5} "
toc-h6 = "{t1}.{t2}.{t3}.{t4}.{t5}.{t6} "
table = "Table {t}"
image = "Image {i}"
fence = "Fence {f}"
```
