### ISSUE TITLE
关于kanban

### ISSUE THREAD

**Issue by YingZhouK** [obgnail/typora_plugin#971]
![Image](https://github.com/user-attachments/assets/0b9080c1-72a8-40d8-bd22-50b4a82fb98a)

楼主你好，关于这个看板的宽度，能够给个设置项，自动调整 / 固定宽度

强迫症 右边白的看的难受

**Comment by obgnail** [comment]
@YingZhouK 

你好，感谢反馈。有这个设置项呀

```toml
[kanban]
# 看板的宽度（单位：px）
KANBAN_WIDTH = 250
```


此 issue 关闭，如有问题，麻烦在下面留言。
